[itowns] clique molette et deplacement
ign-packo/PackO pull request #103
Opened 2021-02-17 13:21 UTC by ftoromanoff

PR pour permettre le déplacement lors d'un clique molette long.

Question subsidiaire:
- Quel était le problème avec la mise à jour du curseur dans l'ancienne version itowns ?
  J'ai l'impression qu'il n'y a plus de problème (et la suppression des lignes supplémentaire résout un bug d'affichage que j'ai rencontré lors d'une saisie de coordonnées.)

2021-02-23 12:52 UTC, gmaillet commented
Le problème de la mise à jour du curseur: avec la version par défaut d'iTowns lorsqu'on se déplace ou que l'on zoome, le curseur passe à "busy" le temps du déplacement, puis reviens au curseur par défaut, sans prendre en compte que le curseur n'était peut-être pas celui par défaut au départ.
Il faudrait faire une PR pour proposer notre modification au projet iTowns?

2021-02-24 08:41 UTC, ftoromanoff commented
> Le problème de la mise à jour du curseur: avec la version par défaut d'iTowns lorsqu'on se déplace ou que l'on zoome, le curseur passe à "busy" le temps du déplacement, puis reviens au curseur par défaut, sans prendre en compte que le curseur n'était peut-être pas celui par défaut au départ.
> Il faudrait faire une PR pour proposer notre modification au projet iTowns?

J'en ai parlé à Gerald et ai déposé une 'issue'

2021-04-09 14:48 UTC, ftoromanoff commented
> Le problème de la mise à jour du curseur: avec la version par défaut d'iTowns lorsqu'on se déplace ou que l'on zoome, le curseur passe à "busy" le temps du déplacement, puis reviens au curseur par défaut, sans prendre en compte que le curseur n'était peut-être pas celui par défaut au départ.
> Il faudrait faire une PR pour proposer notre modification au projet iTowns?

Corrigé dans la PR #110 Gestion de la forme du curseur

2021-04-12 14:34 UTC, gmaillet commented
@ftoromanoff cette PR est-elle toujours d'actualité?

2021-04-12 14:50 UTC, ftoromanoff commented
> @ftoromanoff cette PR est-elle toujours d'actualité?

Oui, pour le but dans lequel a été ouverte cette PR => pouvoir faire un clique molette.
LA question subsidiaire qui a été ensuite développé ici a été résolue dans la PR #110

2021-04-27 10:45 UTC, gmaillet requested changes
La suppression du patch sur la gestion du curseur introduit une régression dans cette PR (mais c'est peut-être géré dans une autre PR, je n'ai pas encore vérifié).
Exemple: on commence un saisie (le curseur passe en croix), on zoome (le curseur passe en sablier le temps du zoom), lorsque le zoom est terminé on se retrouve avec le curseur par défaut au lieu de la croix.
Par contre, le fonctionnement du déplacement pendant une saisie est très bien.

2021-04-27 11:48 UTC, merged