[API] dynamique tileSize
ign-packo/PackO pull request #114
Opened 2021-03-30 14:50 UTC by ftoromanoff

Objectif:
- Pouvoir faire des retouches sur un cache qui n'est pas constitué de tuiles 256 * 256

2021-03-30 17:12 UTC, gmaillet requested changes
dommage d'ajouter le paramètre tileSize alors que les objets de type bitmap ont les champs width et height

2021-03-31 09:27 UTC, gmaillet approved these changes
Je ne sais pas si cela règle tous les problèmes, mais c'est clairement une amélioration du code existant.

2021-03-31 16:11 UTC, amrosu approved these changes

2021-03-31 16:19 UTC, amrosu commented
J'ai fait des tests avec caches avec différentes tailles de tuile (256, 512, 1024) et les retouches sont bien prises en compte

2021-04-01 11:52 UTC, merged