[graph.js] Modif code retour get graph
ign-packo/PackO pull request #115
Opened 2021-03-31 15:23 UTC by ftoromanoff

Objectif:
- retourner un code 201 lorsque l'OPI est "missing"

Ajout d'un code 'out of graph' pour un get OPI dans la bordure noire du graph

2021-04-27 11:01 UTC, gmaillet requested changes
Je ne suis pas trop convaincu par la nécessité de la PR et je crains qu'elle ne permette plus de détecter des incohérences éventuelles sur notre cache (ce qui est important).

2021-04-27 11:01 UTC, gmaillet commented on routes/graph.js
> +        if (out.color.some((item) => item !== 0)) {
Avant, on vérifié si la couleur recherchée était effectivement dans le dictionnaire. Maintenant, on teste simple s'il y a au moins une couleur dans le dictionnaire (si j'ai bien compris le some).
Normalement, si le cache est cohérent, pas de problème: on devrait toujours avoir la couleur. Mais avant l'ancien code on avait un message de retour si ça n'était pas le cas, avec le nouveau code on aura une erreur NodeJS dans l'API et pas de réponse à l'utilisateur.

2021-05-12 13:44 UTC, ftoromanoff commented on routes/graph.js
> +        if (out.color.some((item) => item !== 0)) {
Corrigé

2021-05-19 07:29 UTC, gmaillet approved these changes
Fonctionnellement je confirme que c'est ok. 
Reste à nettoyer les commits, on peut en profiter pour appliquer les nouvelles convention pour les messages svp

2021-05-20 09:41 UTC, merged