léger Cleanup
ign-packo/PackO pull request #116
Opened 2021-04-08 13:56 UTC by ftoromanoff

Cette PR propose : 

- une homogénéisation du code serveur.js (utilisation de path.join)
- une modification du retour de la fonction permettant de retourner le chemin des tuiles rok4
- une correction de bug lié au 'clear'

2021-04-12 14:28 UTC, gmaillet requested changes
Je n'ai pas encore testé, je trouve que les modifications sont bonne (gestion plus propre des chemins), mais je pense qu'on peut aller encore un peu plus loin en factorisant une fois pour toute la construction des chemins au niveau de tile.
Par contre, je n'ai pas bien compris quel est le bug de clear que l'on cherche à corriger: je vois que cela se passe sans doute dans la suppression des images des unactivePatchs mais ça n'est pas simple à valider sans avoir d'information sur le bug et la façon de le reproduire.

2021-04-12 14:28 UTC, gmaillet commented on routes/patch.js
> +    const urlGraphSelected = path.join(global.dir_cache, 'graph', tileRoot.dirPath, `${tileRoot.fileName}_${patchIdRedo}.png`);
pourquoi ne pas créer des variables graphDir et orthoDir pour être cohérent avec ce qui est fait plus bas (lignes 394/395)?

2021-04-12 14:28 UTC, gmaillet commented on routes/patch.js
> +      const orthoDir = path.join(global.dir_cache, 'ortho', tileRoot.dirPath);
du coup, on pourrait ajouter opiDir pour être cohérent et corriger la ligne 390

2021-04-12 14:28 UTC, gmaillet commented on routes/patch.js
> +    const urlGraph = path.join(global.dir_cache, 'graph', tileRoot.dirPath, `${tileRoot.fileName}.png`);
pourquoi ne pas créer des variables graphDir et orthoDir pour être cohérent avec ce qui est fait plus bas (lignes 394/395)?

2021-04-12 14:28 UTC, gmaillet commented on routes/patch.js
> +    const urlHistory = path.join(global.dir_cache, 'opi', tileRoot.dirPath, `${tileRoot.fileName}_history.packo`);
du coup, on pourrait ajouter opiDir pour être cohérent et corriger la ligne 390

2021-04-12 14:28 UTC, gmaillet commented on rok4.js
> +    fileName: strX[pathDepth] + strY[pathDepth],
on pourrait créer dès maintenant les opiDir, graphDir et orthoDir dont on a besoin un peu partout dans le code?

2021-04-14 13:33 UTC, ftoromanoff commented
> Par contre, je n'ai pas bien compris quel est le bug de clear que l'on cherche à corriger: je vois que cela se passe sans doute dans la suppression des images des unactivePatchs mais ça n'est pas simple à valider sans avoir d'information sur le bug et la façon de le reproduire.

Transféré vers une autre PR (la PR #122 )

2021-04-27 11:16 UTC, gmaillet approved these changes
Testé sur plusieurs caches, ça me semble ok.
Code propre.
RAS

2021-04-27 11:19 UTC, merged