[cache] Recalcul OPI lors d'un update
ign-packo/PackO pull request #123
Opened 2021-04-15 10:00 UTC by ftoromanoff

Objectif : 
- Pouvoir re-traiter en intégralité (découpage et ortho/graph) des OPI déjà traitées.

Modifications : 
- ajout d'une option --recalcul (pris en compte seulement en mode update)
- ajout d'un block try/except de l'ensemble du processus de traitement
- lors du calcul des ortho et graph :
  - regroupement des thread par paquet de 100*cpu
  - création d'un fichier log pour suivre l'évolution de manière chiffrée de ces regroupement

2021-04-27 12:13 UTC, gmaillet requested changes
Pas encore testé, mais déjà quelques remarques sur le code

2021-04-27 12:13 UTC, gmaillet commented on scripts/cache.py
> +                            help="recalcul apres bug",
le help devrait être plus explicite, sans avoir analysé le code je n'ai pas compris ce que faisait l'option

2021-04-27 12:13 UTC, gmaillet commented on scripts/cache.py
> +            for thread in range(0, len(args_create_ortho_and_graph), step):
le nom de la variable thread ne me semble pas bon, on pourrait plutôt parler d'un batch. 
Si j'ai bien compris, tu groupes les traitements en paquet et pour chaque paquet tu crées un pool de (cpu_dispo -1) threads.
Même si ça n'est pas réellement un bug, pour être cohérent il serait logique d'avoir plutôt des paquets de 100*(cpu_dispo - 1) plutôt que 100 * cpu_dispo

2021-04-27 12:13 UTC, gmaillet commented on scripts/cache.py
> +            for arg in args_create_ortho_and_graph:
L'idée du log est bonne, du coup, ça serait intéressant de l'avoir aussi lorsqu'il n'y a pas de multiprocessing, non?

2021-05-26 13:53 UTC, ftoromanoff commented on scripts/cache.py
> +                            help="recalcul apres bug",
J'ai changé recalcul par reprocessing ainsi que le message d'aide

2021-06-07 13:59 UTC, ftoromanoff commented
@gmaillet et @amrosu : J'ai pris en compte les 2 remarques soulevées lors de la dernière réunion PackO.

2021-06-08 08:26 UTC, gmaillet approved these changes

2021-06-08 09:54 UTC, merged