[cache] Warp OPI sous ech et translate
ign-packo/PackO pull request #124
Opened 2021-04-15 12:18 UTC by ftoromanoff

2021-04-30 12:32 UTC, gmaillet requested changes

2021-04-30 12:32 UTC, gmaillet commented on scripts/cache_def.py
> +        if not level == overviews['level']['max']:
Attention, même à pleine résolution il faut faire le Warp pour garantir le phasage

2021-04-30 16:33 UTC, gmaillet commented
J'ai terminé les tests que j'avais commencé sur ma machine (avec 1 OPI Rhone en local). 

- Je constate en effet que le temps est légèrement plus long (en faisant le Reech même au niveau 21): 470s de découpe sur le master, 500s avec la branche.
- J'ai comparé les caches dans QGis, je n'ai pas vu d'écart géométrique (mais il faudra vérifier avec des dalles plus grandes, pas évident sur du 256x256)
- Je trouve la radiométrie de la version de la branche plus belle que celle du master sur les sous-ech (par défaut, sur le master, on fait du 1 pixel/N alors que là on fait de la moyenne niveau par niveau sur cette branche).
- Du coup j'ai refait un essai sans le GRA_Average: la qualité radiométrique est comparable avec celle du master. Par contre, il y a en effet un décalage léger (genre 1/2 pixel). Par contre, le temps est très bon: 380s contre 470s sur le master.
- Je pense qu'on peut faire mieux en n'utilisant le Warp uniquement à la pleine résolution, puis on fait des sous Ech 2 en mémoire. On peut le faire avec un Translate (mais c'est dommage parce que cela inclue l'encodage dans un format, etc...), il faudra le faire avec ReadAsArray etc... mais ça demande plus de travail

2021-05-03 11:24 UTC, gmaillet commented
Nouveau test: j'ai essayé de faire:
- un seul Warp (à la meilleur résolution), puis de charger l'image dans un tableau numpy avec un ReadAsArray
- de faire les sous-ech et les crop des tuiles avec des slices numpy
- de créer chaque tuile en mémoire avec des WriteArray
- de sauver les tuiles en Png avec un CreateCopy
Pas de différence significative de performance avec la version de cette branche (sans le GRA_Average) alors que le code est plus complexe = fausse piste.

Je pense que la priorité c'est de faire fonctionner la version sans le Average en réglant le problème de géoref.

2021-05-03 16:51 UTC, gmaillet commented
J'ai fait quelques essais pour mesurer le décalage avec l'OPI d'origine. Le décalage est très faible et pas simple à estimer, il me semble négligeable aux niveaux de zoom qui nous intéressent.

2021-05-27 10:24 UTC, nlenglet-ign commented
Résultats des tests comparant les branches master et WarpAndTranslate à cette date.
[test_perf_cache.xlsx](https://github.com/ign-packo/PackO/files/6553192/test_perf_cache.xlsx)

2021-07-19 13:24 UTC, closed without merging