fix(monitor): limit zoom to dataset lvls, not default lvls
ign-packo/PackO pull request #142
Opened 2021-05-20 11:26 UTC by ftoromanoff

objectif:
- limiter les niveau de zoom a ceux effectivement calculés, pour le cache en question (+/-1)

2021-05-21 14:30 UTC, amrosu requested changes

2021-05-21 14:30 UTC, amrosu commented on itowns/index.js
> +      minResolution: resolLvMin * zoomFactor,
Les niveaux indiqués par l'utilisateur semblent bien pris en compte à la place des valeurs par défauts.
Mais pour  l'affichage : on a bien le **zoom lmax+1**, 
mais **pas le zoom lmin-1**, l'affichage s'arrête au lmin.
Et je vois que c'était déjà le cas avec le master

2021-05-25 08:30 UTC, amrosu commented on itowns/index.js
> +      minResolution: resolLvMin * zoomFactor,
Il faudrait se décider si on veut s'arrêter pile sur les niveaux calculés pour le cache, sans donner la possibilité d'aller au zoom +/-1. Si oui, alors pas besoin de corriger le problème avec zoom -1, il faudrait seulement enlever le zoom +1

2021-05-25 08:52 UTC, ftoromanoff commented on itowns/index.js
> +      minResolution: resolLvMin * zoomFactor,
Il semblerait que se soit un problème dans itowns. J'ai demandé a Madek et ouvert une issue.

2021-05-25 16:21 UTC, amrosu commented on itowns/index.js
> +      minResolution: resolLvMin * zoomFactor,
Comme la correction de la prise en compte des niveaux calculés à la place des niveaux par défaut (#134) est effective, je propose de fusionner cette branche dans master.
Et j'ai ouvert un autre ticket (#149) pour s'occuper du problème de ré-échantillonnage dans le moniteur

2021-05-26 08:20 UTC, merged