Gestion de cache en COG
ign-packo/PackO pull request #158
Opened 2021-06-25 12:21 UTC by gmaillet

# Motivation

Améliorer les perfs de création de cache, y compris sur le serveur et le store de la prod.

# Principe

On fait des dalles de tuiles en COG: typiquement des images de 4096x4096 avec un blockSize à 256. Ceci permet d'avoir un deZoom 16 dans le COG.
On utilise une compression Jpeg 90 pour les OPI et l'Ortho, une compression LZW pour le graph.

L'avantage, c'est que ce format est bien géré nativement par GDAL (à partir de la version 3.2).

2021-06-30 13:36 UTC, ftoromanoff requested changes

2021-06-30 13:36 UTC, ftoromanoff commented on cog_path.js
> +  if (factor > nbTiles) {
Il faudrait peut être utiliser des termes plus clair pour ce test.
On compare un 'factor' (qui est le dezoom) a un nbTiles. Ca marche dans ce cas ou tout est multiple de 2.

Autre point niveau de la gestion de l'erreur soulevée, il n'y a que dans route/wmts.js a la ligne 282 que l'appel a getTilePath est dans un try/catch.
Pas de gestion d'erreur a la ligne 311 ni dans routes/graph.js

2021-06-30 13:36 UTC, ftoromanoff commented on routes/graph.js
> +  const cogPath = cog.getTilePath(Tx, Ty, lvlMax, overviews);
gestion des erreurs ?

2021-06-30 13:36 UTC, ftoromanoff commented on routes/wmts.js
> +      // à pleine résolution
pour coherence avec le standard WMTS, il faudrait les avoir pour tous les niveaux existant :
Soit en les calculant a la volée ici, soit en les calculant lors de la création du cache (pour garder la structure avant COG)

2021-07-01 14:04 UTC, gmaillet commented
Je passe la branche en WIP pour traiter les questions soulevées par la review de François

2021-07-05 11:50 UTC, gmaillet commented on .github/workflows/coveralls.yml
> +        sudo add-apt-repository ppa:ubuntugis/ppa && sudo apt update
cela a été vérifié

2021-07-13 12:33 UTC, gmaillet commented
Repris dans #162

2021-07-13 12:33 UTC, closed without merging