Gestion de cache en COG (version 2)
ign-packo/PackO pull request #162
Opened 2021-07-13 12:29 UTC by gmaillet

2021-07-13 13:12 UTC, ftoromanoff requested changes
Je teste le code

2021-07-13 13:28 UTC, gmaillet commented on itowns/index.js
> +  const minZoom = maxZoom - arrayLimits.length + 1;
En effet, je vais faire la correction.

2021-07-13 13:37 UTC, ftoromanoff commented on itowns/index.js
> +  const resolLvMax = resolution * 2 ** (overviews.level.max - maxZoom - 1);
En permettant d'aller un niveau plus loin que ce qui est dans le dataset.limits on se retrouve forcement avec itowns qui interroge l'entièreté de la zone et donc plein de petites tuiles noires.
On devrait peut être forcer le calcul du niveau Max+1 au niveau du cache ou alors ne pas permettre d'y aller.

Ne serait il d'ailleurs pas mieux de mettre le '+1' au niveau de la 'view' ?

2021-07-13 13:45 UTC, gmaillet commented on itowns/index.js
> +  const resolLvMax = resolution * 2 ** (overviews.level.max - maxZoom - 1);
Avec des dalles de 4096 en COG on ne peut avoir que le DeZoom16, or le SIA veut absolument le DeZoom32 (ils voudraient même plus).
Donc,

- soit on fait des dalles COG 9192, mais ça va nous coûter en temps de mise à jour des patchs
- soit on fait une deuxième couche de COG, mais ça ne me paraît pas indispensable sur cette PR

Sinon, je n'ai pas compris la dernière question sur le "+1" au niveau de la "view".

2021-07-15 12:49 UTC, amrosu requested changes
Il faudrait enlever l'option utilisateur "-l" pour la création cache COG, car elle n'est pas correctement gérée. Et comme cette option était surtout très utile pour la création des cache "anciens", sans COG (surtout pour une question de temps de calcul), on peut s'en séparer pour les caches COG, au moins dans un premier temps et la remettre si besoin ressenti ou demande utilisateur

Et j'ai l'impression (c'est juste une impression pour le moment) que les saisies prennent un peu plus de temps qu'avant (ex: il y a un minimum de 5 s d'attente, même pour les toutes petites sur un cache de 4 OPI) - à vérifier

2021-07-15 13:47 UTC, amrosu commented
Dans le moniteur, il reste un petit problème sur la visibilité/opacité de la couche graphe : l'opacité ne devrait pas descendre en-dessous de la valeur par défaut (0.001), car à 0 on retombe sur les problèmes décrits dans ma révision de la PR #136.

2021-07-15 15:15 UTC, gmaillet commented
> Il faudrait enlever l'option utilisateur "-l" pour la création cache COG, car elle n'est pas correctement gérée. Et comme cette option était surtout très utile pour la création des cache "anciens", sans COG (surtout pour une question de temps de calcul), on peut s'en séparer pour les caches COG, au moins dans un premier temps et la remettre si besoin ressenti ou demande utilisateur
> 
> Et j'ai l'impression (c'est juste une impression pour le moment) que les saisies prennent un peu plus de temps qu'avant (ex: il y a un minimum de 5 s d'attente, même pour les toutes petites sur un cache de 4 OPI) - à vérifier

ok, je m'occupe de supprimer l'option "-l". 
En ce qui concerne les performances: c'est malheureusement probable. La moindre micro retouche nous oblige à ré-écrire un COG de 4096x4096, j'observe en effet un temps autour de 5s. Par contre, je pense qu'on aura souvent une seule dalle de touchée, donc on devrait rester souvent autour de 5s. Au pire, on aura 4 dalles touchées et on peut s'attendre à 20s. Pour le moment, je crois que l'on ne pourra faire mieux...

2021-07-16 08:36 UTC, amrosu commented
OK pour moi.
Je pense qu'il faudrait qu'on fasse aussi des tests windows sur un cache assez gros qui se trouve sur un store, en essayant donc de se mettre en conditions de prod autant que possible

2021-07-16 08:36 UTC, amrosu approved these changes

2021-07-16 10:03 UTC, ftoromanoff commented on itowns/index.js
> +  const resolLvMax = resolution * 2 ** (overviews.level.max - levelMax - 1) - 0.01;
Au vue de la façon dont itowns gère le rafraichissement de la vue et les requêtes http, ne faudrait il pas mieux bloquer la resolutionMax au niveau levelMax (du dataset, et nom du dataset +1) ?
Autre petite remarque, resolLvlMax ne correspond pas à la résolution du level Max, pour une clarté des noms de variable peut être juste mettre resolMax (ou resolViewMax).

2021-07-16 11:46 UTC, merged