Gestion des branches de cache basé sur les caches en COG
ign-packo/PackO pull request #163
Opened 2021-07-15 09:27 UTC by gmaillet

# Motivation

Pouvoir avoir plusieurs version des modifications du cache sous forme de branches. C'est la première étape pour la gestion du travail collaboratif sur PackO (c'est-à-dire à plusieurs sur un même cache). Pour éviter les conflits et les incohérences, chaque utilisateur devra travailler seul, sur sa branche. Il faudra ajouter des outils de fusion de branches ainsi que des vérifications permettant de s'assurer que deux personnes ne travaillent pas en même temps sur une branche.

2021-07-16 13:19 UTC, amrosu requested changes
Dans le moniteur itowns, le contenu du "message" devrait être réinitialisé lors du changement de la branche, car si il reste sur un message d'une branche, il n'a pas de sens sur une autre

2021-07-16 13:19 UTC, amrosu commented on doc/swagger.yml
> +  '/{branchId}/patchs/clear':
corriger "patchs" -> "patches" partout dans tout le code

2021-07-19 14:44 UTC, amrosu requested changes

2021-07-19 14:44 UTC, amrosu commented on routes/branch.js
> +    res.status(406).send('A branch with this name already exists');
Il serait pas mal de raccourcir ce message, car il est trop long pour être affiché en entier

2021-07-20 07:37 UTC, nlenglet-ign commented on itowns/Saisie.js
> +    if (branchName === null) return;
Les noms contenant uniquement des caractères spéciaux fonctionnent également, il faudrait peut être vérifier que le nom d'une branche contient au minimum un caractère alphanumérique.

2021-07-20 13:48 UTC, gmaillet commented on itowns/Saisie.js
> +    if (branchName === null) return;
ok pour vérifier que la chaine n'est pas vide.
Pour les caractères spéciaux: je vais tester, mais si l'utilisateur veut appeler sa branche '???' qu'on le gère correctement, pourquoi pas?

2021-07-20 13:49 UTC, gmaillet commented on routes/branch.js
> +    res.status(406).send('A branch with this name already exists');
bien vu, je m'en occupe

2021-07-21 10:27 UTC, merged