[monitor] Visualisation des saisies
ign-packo/PackO pull request #173
Opened 2021-07-23 15:28 UTC by ftoromanoff

PR pour la visualisation des patchs en cours.

Modifications:

utilisation du async pour le Fetcher
ajout d'une couche a partir du json de GET patches

2021-08-30 06:54 UTC, nlenglet-ign commented
Testé sous Edge.
Pas de soucis particulier rencontré.
Pas de revue de code effectué.

2021-09-02 11:59 UTC, gmaillet requested changes
Avant d'avoir relu le code quelques remarques après avoir testé:

- lorsqu'on crée une branche les saisies de la branche précédente restent visibles et les nouvelles saisies ne s'affichent pas
- lorsqu'on ajoute un patch, il y a un effet de "flash" lors de l'affichage (écran jaune, avant l'affichage fin)
- c'est souvent perturbant de voir les patchs en superposition des contours du graphe: je pense que les utilisateurs vont demander que la couche ne soit pas visible par défaut.

2021-09-03 13:16 UTC, ftoromanoff commented
> Avant d'avoir relu le code quelques remarques après avoir testé:
> 
> * lorsqu'on crée une branche les saisies de la branche précédente restent visibles et les nouvelles saisies ne s'affichent pas
Corrigé, ca venait de la gestion des branche (PR precedente)

> * lorsqu'on ajoute un patch, il y a un effet de "flash" lors de l'affichage (écran jaune, avant l'affichage fin)
Gestion de l'affichage par itowns, j'en avais parlé a Gerald, mais on ne peut rien faire de notre coté.

> * c'est souvent perturbant de voir les patchs en superposition des contours du graphe: je pense que les utilisateurs vont demander que la couche ne soit pas visible par défaut.

Je pourrais changer ça dans un second temps, si demande

2021-09-03 14:48 UTC, amrosu approved these changes
Tests faits avec la dernière version après corrections et cela semble être OK.

Je suis d'accord avec @gmaillet, le côté disco flash sur les saisies rechargées est assez perturbant, mais il faut voir ce que l'équipe itowns peut faire pour l'améliorer (de notre côté, on peut peut-être utiliser une autre couleur que le jaune pétant, mais à modifier uniquement si l'utilisateur final le demande).

Et sinon, j'ai vu que la couche Patches semble être touchée aussi par des problèmes itowns visibility/opacity décrits dans #164 sur la couche Graph, je ferai une suite au ticket #164 et on verra si correction possible de côté de l'équipe itowns.

2021-09-03 14:57 UTC, amrosu commented
Une solution temporaire de contournement des problèmes avec visibility/opacity d'itowns est de mettre la val min pour l'opacité > 0 (comme  sur la couche Graph) - pas complètement satisfaisant, mais ça limite les dégâts ;)

2021-09-09 08:41 UTC, gmaillet approved these changes

2021-09-10 13:33 UTC, merged