Route db clean
ign-packo/PackO pull request #201
Opened 2021-09-27 11:24 UTC by ftoromanoff

2021-09-28 14:00 UTC, nlenglet-ign reviewed
Testé sous Windows : 
- cache intégré dans la base de données sans soucis
- branches toujours opérationnelles (y compris affichage de leurs patches associés)
- les interactions liées aux patches fonctionnent comme attendu (y compris suppression des patches qui ne sont plus utilisés dans la base de données

2021-09-30 12:57 UTC, amrosu requested changes
Les nouvelles fonctionnalités ajoutées avec la base de données semblent bien marcher avec l'API et BD en local.
Il faudrait maintenant voir le fonctionnement sur VM

2021-09-30 12:57 UTC, amrosu commented on middlewares/branch.js
> +      msg: `Impossible de détruire la branche : '${idBranch}'`,
traduire en anglais, comme les autres msg

2021-09-30 12:57 UTC, amrosu commented on middlewares/cache.js
> +      msg: `Impossible de détruire le cache : '${idCache}'`,
idem

2021-09-30 12:57 UTC, amrosu commented on package.json
> +    "pg-format": "^1.0.4",
pousser une version à jour du package-lock.json, car dans la version actuelle il manque "pg-format" et nous sommes donc en "dirty"

2021-10-01 11:55 UTC, ftoromanoff commented on itowns/Saisie.js
>        this.message = 'le nom n\'est pas valide';
La fenêtre message reçoit des messages en français, mais il y a effectivement parfois des messages en anglais (ex: 'nothing to redo') je pense que c'est plutôt ceux ci qu'il faudrait passer en français.
Je peux corriger ca plutôt dans la PR suivante qui s'intéresse surtout a la partie itowns.

2021-10-01 14:12 UTC, amrosu commented on itowns/Saisie.js
>        this.message = 'le nom n\'est pas valide';
Vu que les actions du menu itowns sont en anglais (à part cliche qu'on devrait traduire), il est normal de mettre aussi les messages en anglais, comme fait jusqu'à maintenant

2021-10-01 14:23 UTC, ftoromanoff commented on itowns/Saisie.js
>        this.message = 'le nom n\'est pas valide';
Les messages ont toujours principalement été en français (pour le menu message).
Ne faudrait il mieux pas traduire le menu en Français ?

2021-10-01 14:27 UTC, amrosu commented on itowns/Saisie.js
>        this.message = 'le nom n\'est pas valide';
Non, on peut dire que le menu est en anglais et le laisser et traduire le seul message du menu qui était en français, mais si on diverge à cause de ça et on perd trop de temps avec ça, c'est mieux de laisser de franglais et avancer

2021-10-01 14:44 UTC, amrosu commented on itowns/Saisie.js
>        this.message = 'le nom n\'est pas valide';
Ma demande initiale était bien simple, elle concernait un seul message et ça ne demandait pas de changer tout dans le menu. La cohérence était assurée avec un toute petite modification - traduction en anglais d'un tout petit message et donc je pensais qu'on pouvais régler ça rapidement dans cette PR, ce n'était pas grande chose. La remise à plat de tout le menu n'est pas nécessaire, pas d'actualité, et pas demandé et surtout pas le but de cette PR. Il est donc suffisant de se rester à ma demande initiale

2021-10-01 16:50 UTC, amrosu approved these changes
Comme je le dit plus bas, si il reste que la mise en cohérence des messages de debug dans db.js, mais ce n'est ni urgent, ni très important pour le moment, on pourrait s'en occuper plus tard
Il faudrait maintenant faire le ménage dans les commits avant "merge"

2021-10-01 16:50 UTC, amrosu commented on db/db.js
> +}
Il reste la mise en cohérence des messages de debug - mais si c'est la seule chose qui reste, on peut s'en occuper dans une autre branche, plus tard, après la livraison même

2021-10-04 07:29 UTC, ftoromanoff commented
> Comme je le dis plus bas, si il reste que la mise en cohérence des messages de debug dans db.js, mais ce n'est ni urgent, ni très important pour le moment, on pourrait s'en occuper plus tard Il faudrait maintenant faire le ménage dans les commits avant "merge"

Je ne comprend pas, cela a normalement été corrigé dans le commit 2f30bc4 : fix(API): suppr space after ':'

2021-10-04 07:52 UTC, amrosu commented
> De manière générale, il serait bien de mettre en cohérence les messages de debug dans db.js et enlever l'espace avant ":"
Une partie de cette demande a été prise en compte (suppression de l'espace), mais la mise en cohérence des massages dans db.js n'a pas été gérée : il y a des messages sans aucune info, d'autres avec une information bien complète et d'autres pas très claires...
Mais je propose (voir plus haut, dans mon message de validation de cette PR) de fusionner cette branche et faire cette mise en cohérence plus tard sur une autre branche. Il faut se concentrer sur la livraison et cette mise en cohérence est moins importante en ce moment que le reste des PR à fusionner pour la prochaine livraison de cette semaine.

2021-10-04 08:46 UTC, amrosu commented
Merci @ftoromanoff  pour le nettoyage des commits.

Il reste quelques petites choses sur les commits :
- les "types" de commits ne sont pas toujours respectés : on a plusieurs commits avec des "feat" + "fix" ensemble dans un même message (ex: 2fe0019), "build" + "fix" (ex: d8d965c) -> séparer les commits par type 
- il reste un commit en français (87e2cad) -> à traduire
- dans d8d965c, chronologie -> chronology

2021-10-04 10:04 UTC, amrosu commented
J'ai refait quelques tests avant le "merge" et je vois qu'on ne gère pas bien le "namecache" : dans le cas où le cache indiqué n'existe pas, le premier cache de la base est chargé et on n'a aucun message d'erreur indiquant que le cache demandé n'existe pas.
Je vous propose néanmoins de gérer ce problème dans une autre branche et de fusionner celle-ci. Est-ce que c'est bon pour vous ?

2021-10-04 10:07 UTC, ftoromanoff commented
> J'ai refait quelques tests avant le "merge" et je vois qu'on ne gère pas bien le "namecache" : dans le cas où le cache indiqué n'existe pas, le premier cache de la base est chargé et on n'a aucun message d'erreur indiquant que le cache demandé n'existe pas. Je vous propose néanmoins de gérer ce problème dans une autre branche et de fusionner celle-ci. Est-ce que c'est bon pour vous ?

C'est bon pour moi

2021-10-04 11:35 UTC, gmaillet approved these changes
Je n'ai pas le temps de tester à fond mais ce que j'ai vu me semble bien.
c'est bon pour moi.

2021-10-04 11:58 UTC, merged