docs(cache|API|db): documentation update with db
ign-packo/PackO pull request #203
Opened 2021-09-29 09:00 UTC by gmaillet

# Motivation

Mise à jour de la documentation:
- structure de laBD
- création et import d'un cache

Le schéma de la BD a été fait avec https://www.diagrams.net/, l'image est dans doc/BD_packo.drawio.png. Ce fichier est un PNG qui est inclue dans le README.mk, mais il est également éditable dans draw.io.

2021-09-29 09:03 UTC, gmaillet commented
Petite remarque: le schéma est basé sur la BD de la branche (RouteDB_clean) et non sur celle de RouteDB.

2021-09-29 09:39 UTC, amrosu requested changes
Cette doc est bien complète :+1:

2021-09-29 09:39 UTC, amrosu commented on README.md
> +python scripts/create_cache.py -i "regress/data/*.tif" -o ressources/LAMB93_5cm.json -c cache_regress -g "regress/data/regress_graphe.gpkg" -t graphe
Mettre cet exemple de commande après la commande générique (qui est plus bas)

2021-09-29 09:39 UTC, amrosu commented on README.md
> +usage: create_cache.py [-h] -i INPUT [-c CACHE] [-o OVERVIEWS] [-g GEOPACKAGE] [-t TABLE] [-p PROCESSORS] [-v VERBOSE]
remplacer "usage:" par "python"

2021-09-29 09:39 UTC, amrosu commented on README.md
> +python scripts/update_cache.py -i "regress/data/update/*.tif" -c cache_regress -g "regress/data/regress_graphe.gpkg" -t graphe
Remplacer par une commande générique

2021-09-29 09:39 UTC, amrosu commented on README.md
> +- le contenu du fichier overviews.json (celui qui a été créé par le script python)
pour plus de clarté, ajouter à la fin "et correspondant au cache à importer"

2021-09-29 09:39 UTC, amrosu commented on README.md
> +shp2pgsql /Volumes/PAOT\ 21/ZoneTestPCRS/Graphe/Graphe_PCRS56_ZONE_TEST.shp | psql -d pcrs
modifier le chemin et le nom du shp en indiquant un chemin et un nom génériques

2021-09-29 09:39 UTC, amrosu commented on README.md
>  - un flux WMTS permettant d'accéder aux OPI: ce flux est déclaré comme une couche unique (opi) et on utilise un paramètre de dimension pour choisir le cliché à afficher. Attention, il faut normalemen
l'astuce est toujours à trouver ou plus d'actualité ?

2021-09-29 09:39 UTC, amrosu commented on README.md
> +npm start
ajouter l'option "-p" pour le port et en indiquant que le port par défaut est 8081

2021-09-29 09:39 UTC, amrosu commented on README.md
> +npm start-dev
idem

2021-09-29 09:39 UTC, amrosu commented on README.md
> +Pour importer un cache dans la BD packo, il faut utiliser la route POST **cache** de l'API: http://localhost:8081/doc/#/cache/post_cache.
préciser que l'URL indiqué utilise le port par défaut ou mettre un URL générique avec NUMERO_PORT à la place de 8081

2021-09-29 09:39 UTC, amrosu commented on README.md
>  - des outils de retouche du graph de mosaiquage
graph -> graphe

2021-09-29 11:15 UTC, gmaillet commented on README.md
> +python scripts/create_cache.py -i "regress/data/*.tif" -o ressources/LAMB93_5cm.json -c cache_regress -g "regress/data/regress_graphe.gpkg" -t graphe
ok

2021-09-29 11:17 UTC, gmaillet commented on README.md
> +usage: create_cache.py [-h] -i INPUT [-c CACHE] [-o OVERVIEWS] [-g GEOPACKAGE] [-t TABLE] [-p PROCESSORS] [-v VERBOSE]
Il ne s'agit pas de la ligne de commande mais de la doc tel qu'elle est donnée par l'option -h. Je ne vois pas trop pourquoi il faudrait mettre python à la place de usage.

2021-09-29 11:17 UTC, gmaillet commented on README.md
> +python scripts/update_cache.py -i "regress/data/update/*.tif" -c cache_regress -g "regress/data/regress_graphe.gpkg" -t graphe
ok

2021-09-29 11:23 UTC, ftoromanoff commented
Ne faudrait il pas mieux merger ce commit sur RouteDB_clean ?

2021-09-29 11:28 UTC, gmaillet commented on README.md
> +- le contenu du fichier overviews.json (celui qui a été créé par le script python)
ok

2021-09-29 11:31 UTC, gmaillet commented on README.md
> +shp2pgsql /Volumes/PAOT\ 21/ZoneTestPCRS/Graphe/Graphe_PCRS56_ZONE_TEST.shp | psql -d pcrs
ok

2021-09-29 11:33 UTC, gmaillet commented on README.md
>  - un flux WMTS permettant d'accéder aux OPI: ce flux est déclaré comme une couche unique (opi) et on utilise un paramètre de dimension pour choisir le cliché à afficher. Attention, il faut normalemen
ça fonctionne dans QGis sans avoir déclaré explicitement les valeurs mais je pense que ce n'est pas conforme au standard (à vérifier avec @ftoromanoff parce que je n'ai jamais réussi à l'utiliser dans QGis).

2021-09-29 11:35 UTC, gmaillet commented on README.md
> +npm start
ok

2021-09-29 11:35 UTC, gmaillet commented on README.md
> +npm start-dev
ok

2021-09-29 11:36 UTC, gmaillet commented on README.md
> +Pour importer un cache dans la BD packo, il faut utiliser la route POST **cache** de l'API: http://localhost:8081/doc/#/cache/post_cache.
ok

2021-09-29 11:36 UTC, gmaillet commented on README.md
>  - des outils de retouche du graph de mosaiquage
ok

2021-09-29 11:45 UTC, gmaillet commented
Prise en compte des remarques de @amrosu.
@ftoromanoff : c'est comme vous voulez, on peut aussi attendre d'avoir mergé RouteDB_clean avant de s'occuper de cette PR.

2021-09-29 15:22 UTC, amrosu commented on README.md
> +usage: create_cache.py [-h] -i INPUT [-c CACHE] [-o OVERVIEWS] [-g GEOPACKAGE] [-t TABLE] [-p PROCESSORS] [-v VERBOSE]
OK, il faudrait mettre avant "usage" la commande avec l'option pour l'aide ("python scripts/create_cache.py --help")

2021-09-29 15:22 UTC, amrosu commented on README.md
> +
ajouter "python scripts/update_cache.py --help"

2021-09-29 15:25 UTC, amrosu commented on README.md
> +npm start -- -p 8084
à la place de 8084, on pourrait mettre [port]
idem plus bas

2021-09-30 09:34 UTC, amrosu commented on README.md
>  - on rasterise le graphe de mosaiquage et on export pour chaque dalle un COG de graphe (image de graphe avec une couleur par OPI) et un COG de l'ortho assemblée
export -> exporte

2021-09-30 09:34 UTC, amrosu commented on README.md
>  L'interface web est alors accesible à l'adresse : http://[serveur]:[port]/itowns
l'adresse correcte est : http://[serveur]:[port]/itowns/?serverapi=[serveur]&portapi=[port]

2021-09-30 09:37 UTC, amrosu commented on README.md
>  L'interface web est alors accesible à l'adresse : http://[serveur]:[port]/itowns
et ajouter aussi l'info de cache à indiquer dans l'adresse avec "namecache=[namecache]"

2021-09-30 10:03 UTC, gmaillet commented on README.md
> +npm start -- -p 8084
ok

2021-09-30 10:04 UTC, gmaillet commented on README.md
>  L'interface web est alors accesible à l'adresse : http://[serveur]:[port]/itowns
ok

2021-09-30 10:04 UTC, gmaillet commented on README.md
>  - on rasterise le graphe de mosaiquage et on export pour chaque dalle un COG de graphe (image de graphe avec une couleur par OPI) et un COG de l'ortho assemblée
ok

2021-09-30 10:15 UTC, gmaillet commented on README.md
> +
je ne comprends pas l'intérêt de cet ajout?

2021-10-05 08:27 UTC, amrosu approved these changes

2021-10-05 08:54 UTC, merged