Supp Vector on dat.GUI
ign-packo/PackO pull request #229
Opened 2021-11-02 14:16 UTC by ftoromanoff

2021-11-05 15:06 UTC, gmaillet requested changes
Je n'ai pas encore fait une relecture du code mais j'ai testé ça me semble bien.
Par contre: 

- je n'aime pas beaucoup le nom 'annex Vectors', pour être cohérent avec le 'Color Layers' je propose plutôt 'Additionnal Layers' par exemple
- je n'ai pas testé l'affichage des ponctuels: peux-tu ajouter un exemple avec ponctuel dans le dossier regress/data pour simplifier les tests et assurer le suivi des non-regressions

2021-11-05 15:14 UTC, ftoromanoff commented
> Je n'ai pas encore fait une relecture du code mais j'ai testé ça me semble bien. Par contre:
> 
> * je n'aime pas beaucoup le nom 'annex Vectors', pour être cohérent avec le 'Color Layers' je propose plutôt 'Additionnal Layers' par exemple

Je vais changer ca.

> * je n'ai pas testé l'affichage des ponctuels: peux-tu ajouter un exemple avec ponctuel dans le dossier regress/data pour simplifier les tests et assurer le suivi des non-regressions

Il faut attendre la nouvelle version de itowns ou alors se mettre sur une branche qui possède au moins un patch.
Je vais essayer de pousser une couche de point dans regress

2021-11-08 14:34 UTC, amrosu requested changes

2021-11-08 14:34 UTC, amrosu commented on itowns/index.js
> +    viewer.menuGlobe.vectorGui = viewer.menuGlobe.gui.addFolder('Additionnal Layers');
Et il serait bien que ce groupe se déplie automatiquement dès qu'on a chargé au moins un vecteur

2021-11-09 09:15 UTC, amrosu commented on itowns/index.js
> +    viewer.menuGlobe.vectorGui = viewer.menuGlobe.gui.addFolder('Additionnal Layers');
Le groupe se déplie bien automatiquement lors du chargement du premier vecteur

2021-11-09 12:49 UTC, gmaillet requested changes

2021-11-09 12:49 UTC, gmaillet commented on itowns/Editing.js
> +              this.view.notifyChange(this.view.getLayerById('Opi'), true);
Il faudrait faire la même correction en ligne 140

2021-11-09 14:23 UTC, gmaillet approved these changes

2021-11-09 14:55 UTC, amrosu approved these changes

2021-11-09 15:09 UTC, merged