feat(monitor): add a graph visibility widget
ign-packo/PackO pull request #236
Opened 2021-11-05 11:04 UTC by gmaillet

deuxième partie de #233

2021-11-05 13:13 UTC, ftoromanoff requested changes

2021-11-05 13:13 UTC, ftoromanoff commented on itowns/index.html
> +        <span id="spanGraphVisible"> Graph Visible </span>
il faudrait rajouter le style ici :
<span id="spanGraphVisible" style="color:#00FF00"> Graph Visible </span>
pour avoir la même couleur au début et par la suite

2021-11-05 13:13 UTC, ftoromanoff commented on itowns/index.js
> +    document.getElementById('spanGraphVisible').innerHTML = '<p style="color:#FF0000";>Graphe Non Visible</p>';
remplacer par :
document.getElementById('spanGraphVisible').style.color = '#FF0000'
document.getElementById('spanGraphVisible').innerHTML = 'Graphe Non Visible';

Pour ne pas avoir un nouveau paragraphe au sein du 'span'

2021-11-05 13:13 UTC, ftoromanoff commented on itowns/index.js
> +    document.getElementById('spanGraphVisible').innerHTML = '<p style="color:#00FF00";>Graphe Visible</p>';
idem

2021-11-05 13:16 UTC, ftoromanoff commented on itowns/css/View.css
> +    bottom: 50;
du fait de l'enlèvement du <p> on peut redescendre la balise

2021-11-05 14:18 UTC, amrosu commented on itowns/css/View.css
> +
J'ai regardé le css et ça mérite un factorisation car il y a pas mal de choses en doublon (comme ceci) - j'ai commencé à la faire, j'aurai très rapidement un commit à pousser

2021-11-05 14:18 UTC, amrosu commented on itowns/index.html
> +        <span id="spanGraphVisible"> Graph Visible </span>
pour ne pas mettre un style en dur, il serait mieux de passer par le css ; je pourrais m'en occuper aussi

2021-11-05 16:51 UTC, amrosu commented
Refacto du css et dans la gestion du nouveau widget.
Et le message est affiché maintenant que si le graphe n'est pas visible (zoom < 1/32), car je pense que c'est superflu sinon

2021-11-05 16:51 UTC, amrosu commented on itowns/index.html
> +        <span id="spanGraphVisible"> Graph Visible </span>
fait

2021-11-05 16:52 UTC, amrosu commented on itowns/index.js
> +    document.getElementById('spanGraphVisible').innerHTML = '<p style="color:#FF0000";>Graphe Non Visible</p>';
fait dans css

2021-11-05 16:52 UTC, amrosu commented on itowns/index.js
> +    document.getElementById('spanGraphVisible').innerHTML = '<p style="color:#00FF00";>Graphe Visible</p>';
idem

2021-11-05 16:53 UTC, amrosu commented on itowns/css/View.css
> +    bottom: 50;
je l'ai passé à 40; 25 me paraissait un peu petit

2021-11-08 08:26 UTC, gmaillet commented on itowns/index.js
> +  document.getElementById('spanGraphVisibWidget').classList.toggle('not_displayed', dezoom >= 32);
Même remarque que celle de François sur la PR#235: plutôt que la valeur 32 "en dur" on devrait calculer le niveau de zoom max, ou du moins, mettre une valeur cohérente avec celle utilisée pour initialisé les limites d'affichage du graphe (nbSubLevelsPerCOG).

2021-11-08 13:08 UTC, amrosu approved these changes

2021-11-08 14:33 UTC, merged