Gdal process v2
ign-packo/PackO pull request #238
Opened 2021-11-09 09:26 UTC by nlenglet-ign

Ajout d'un tuilage lors du calcul de l'export
Mise à jour du script d'export vecteur (ajout des étapes de merge/dissolve/make_valid)
Mise à jour de la doc en conséquence

2021-11-09 09:27 UTC, nlenglet-ign commented
Test en cours sur un cache de 15 OPIs

2021-11-09 10:32 UTC, nlenglet-ign commented
Lors de mes tests, j'ai utilisé tile_size = 25000? La valeur par défaut pose des soucis lors de l'allocation mémoire pour le gdal_retile mais cela devrait fonctionner dans les conditions de prod (serveurs du SIA)

2021-11-09 12:24 UTC, nlenglet-ign commented
![calcul_vectorise_15OPIs](https://user-images.githubusercontent.com/58478624/140923685-05bf00a8-ff8f-426b-8ece-f2d3ba1fc80f.PNG)
Pour info, temps de calcul sur un cache constitué des 15 OPIs Vexcel (taille des tuiles à 25k*25k pixels)

2021-11-09 12:40 UTC, nlenglet-ign commented
A titre de comparaison, les performances avec la version non tuil
![calcul_vectorise_15OPIs_master](https://user-images.githubusercontent.com/58478624/140925986-a225af23-acbf-4c40-b032-301b0ea1ae3e.PNG)
ée

2021-11-17 14:21 UTC, nlenglet-ign commented
Tests réalisés avec le nouveau tuilage sur le cache de 15OPIs du Rhone : 
Avec des tuiles de 25k² pixels
![cache_15OPIs_25K](https://user-images.githubusercontent.com/58478624/142217885-4296aa76-7dcb-480d-9e17-8ed4b9daaa7e.PNG)
Avec des tuiles de 100k² pixels
![cache_15OPIs_100K](https://user-images.githubusercontent.com/58478624/142217922-8bc79ffc-56dc-4808-933c-9ea812744d2f.PNG)

2021-11-17 14:22 UTC, nlenglet-ign commented
Il reste un bug au niveau des attributs récupérés dans le gpkg, l'attribut correspondant à la couleur du label (DN par défaut) disparaît lors de l'étape de dissolve (utilisation de ST_Union), je cherche à corriger le problème, les données risquant de ne pas être exploitables sans cela.

2021-11-19 09:00 UTC, gmaillet reviewed
Je n'ai pas encore testé, mais voilà quelques questions/remarques sur le code

2021-11-19 09:12 UTC, nlenglet-ign commented on scripts/vectorise_graph.py
> +# soit dans tous les cas des tuiles de 100k*100K pixels
Ce commentaire date un peu, ça retranscrivait plus ce que m'avait dit Franck quand ils faisaient de la vectorisation en tuilant. Je vais le supprimer.

2021-11-19 09:32 UTC, nlenglet-ign commented on scripts/vectorise_graph.py
> +y_max = int((float(y_max) // 1000 + 1) * 1000)
Ce bloc de code correspond au calcul de la bbox englobante, il s'agit juste de se caler sur des coordonnées entières en kilomètre.

2021-11-19 09:33 UTC, nlenglet-ign commented on scripts/vectorise_graph.py
> +tmp_dir = os.path.join(args.output, 'tmp')
Ce dossier permet de faire tout le calcul mais une fois dedans, chaque tuile possède un nom différent (ses coordonnées en pratique), à voir si cela pose soucis avec la parallélisation future?

2021-11-19 09:33 UTC, gmaillet requested changes
- Sous MacOS il y a un problème avec la commande ogrmerge (il faut le .py).
- Je constate aussi que la commande ne fonctionne qu'avec des chemins en absolu (ça n'est pas dramatique, mais il faut au minimum le signaler dans la doc).
- Il faut mettre à jour la doc pour enlever la remarque "A l'heure actuelle, ce script ne fonctionne que sur des jeux de données relativement petits. Des évolutions sont en cours pour pallier à ce problème."

2021-11-19 10:48 UTC, nlenglet-ign commented on scripts/vectorise_graph.py
> +# soit dans tous les cas des tuiles de 100k*100K pixels
Fait.

2021-11-19 10:48 UTC, nlenglet-ign commented on README.md
> +                        tile size for vectorising graph tiles (default: 100000)
Fait.

2021-11-19 13:45 UTC, gmaillet requested changes

2021-11-19 13:45 UTC, gmaillet commented on scripts/vectorise_graph.py
> +    'ogrmerge'
tu as bien déclaré un script_merge multi Os, mais tu continues à utiliser ogrmerge en dur

2021-11-19 14:09 UTC, nlenglet-ign commented on scripts/vectorise_graph.py
> +    'ogrmerge'
C'est maintenant bon, oubli de ma part.

2021-11-19 17:06 UTC, gmaillet requested changes
testé sur MacOS avec un cache_test: ça fonctionne bien.
Pour bien faire il faudrait encore:

- nettoyer les commits
- améliorer les sorties dans la console:
  - il y a des messages un peu perturbant pour l'utilisateur "Skipping line   </VRTRasterBand>"
  - il y a de belles barres de progression (celle des commandes GDAL) mais on ne sait pas à quelles étapes elles correspondent: un petit commentaire avant permettrait d'informer l'utilisateur

2021-11-22 07:42 UTC, nlenglet-ign commented
Les messages du type "skipping line" ne devraient plus apparaître.
Concernant les sorties console, en utilisant l'option verbose (avec valeur > 0), je pense que c'est plus explicite, est-ce qu'il faudrait également supprimer les barres de progression gdal dans une version non verbeuse du script ?

2021-11-22 08:19 UTC, gmaillet commented
> 

Je pense que si la barre de progression est affichée il faut que l'utilisateur sache ce qui se passe. Donc:

- soit tu affiches un peu plus d'info lorsque verbose est à zéro
- soit tu lances les commandes gdal en mode "quiet" lorsque le verbose est à zéro

Perso, j'ai plutôt une préférence pour la première solution parce qu'il est intéressant d'avoir une barre de progression sur des commandes aussi longues.

2021-11-22 08:30 UTC, nlenglet-ign commented
Je viens de pousser les modifications en privilégiant la première solution.
Je prépare le nettoyage des commits en parallèle.

2021-11-22 08:51 UTC, nlenglet-ign commented
Rebase fait.

2021-11-22 11:15 UTC, gmaillet approved these changes

2021-11-22 11:22 UTC, merged

2021-11-22 11:48 UTC, amrosu requested changes

2021-11-22 11:48 UTC, amrosu commented on scripts/vectorise_graph.py
>  id_branch = args.branch
Je suis en train de tester et je vois que le param -b n'est pas bien pris en compte, car si la valeur indiquée pour id_branch n'existe pas, j'ai l'impression qu'il se rabat sur la branche orig, ce qui n'est pas souhaitable

Il faudrait renforcer la vérification sur id_branch (l122-126)