refactor: send error if not patch for id_branch
ign-packo/PackO pull request #248
Opened 2021-11-23 15:43 UTC by nlenglet-ign

S'assurer qu'il n'y a bien des patches sur la branche qu'on souhaite exporter si elle est différente de orgi.

2021-11-24 10:02 UTC, amrosu commented on scripts/vectorise_graph.py
> +    raise SystemExit('Il n\'y a pas de patch dans la branche dont l\'id est '+str(args.branch)+'.')
Je viens de pousser cette petite correction sur le message de l'exception, pour l'activer ;)

2021-11-24 10:03 UTC, amrosu commented on scripts/vectorise_graph.py
> +    raise SystemExit('Il n\'y a pas de patch dans la branche dont l\'id est '+str(args.branch)+'.')
Sans ça, il ne prenait pas en compte cette exception et le id_branch restait donc mal géré

2021-11-24 10:17 UTC, nlenglet-ign commented on scripts/vectorise_graph.py
> +    raise SystemExit('Il n\'y a pas de patch dans la branche dont l\'id est '+str(args.branch)+'.')
Ah oui, bien vu, c'était un oubli de ma part.

2021-11-24 13:12 UTC, amrosu commented
et une petite correction sur le type de la variable pour que la condition soit prise en compte

2021-11-24 13:19 UTC, amrosu requested changes

2021-11-24 13:19 UTC, amrosu commented on scripts/vectorise_graph.py
>  patches = patches_data['features']
Le cas d'une branche de saisies sans aucune saisie ( patches = [ ]) n'est pas géré.

@nlenglet-ign : je te laisse la main ou je le fais ?

2021-11-24 13:30 UTC, nlenglet-ign commented on scripts/vectorise_graph.py
>  patches = patches_data['features']
Je regarde ça

2021-11-24 13:44 UTC, nlenglet-ign commented on scripts/vectorise_graph.py
>  patches = patches_data['features']
Correction poussée

2021-11-25 10:48 UTC, amrosu commented
J'ai fait des corrections dans les tests, pour traiter les cas pas pris en compte.

2021-11-25 14:26 UTC, amrosu approved these changes

2021-11-26 13:11 UTC, merged