fix(API): fix GeoTransform on cache
ign-packo/PackO pull request #249
Opened 2021-11-24 13:09 UTC by gmaillet

# Motivation 

Depuis le commit 3b673edd459d3b87127150a6786288ff42fa7404 les COG modifiés dans le cache (pour l'ortho et le graph) n'ont ni géoref ni SRS.

# Principe

Il faut ajouter la copie du geoTransform et du srs.
Attention:

- il faut faire attention à bien utiliser les API Async
- il peut y avoir des interférences avec une config locale de GDAL: en particulier la variable PROJ_LIB. Dans ce cas, le SRS peut être non reconnu et l'image obtenu s'affiche dans QGis en SRS inconnu. Dans ce cas, faire un "unset PROJ_LIB" avant de lancer l'API

2021-11-24 14:39 UTC, ftoromanoff commented
Sous ma session PORJ_LIB=C:\IGN\SolVeg\nad par défaut. (Ce que je ne peux pas modifier, vu qu'il faut le compte admin et avec celui-ci je ne peux modifier que les variables d'environnement du compte admin...)
Mon premier test d'application de patch a échouer avec une erreur :
(node:19416) UnhandledPromiseRejectionWarning: Error: Unsupported SRS
    at D:\PackO\gdal_processing.js:170:17
Mon deuxième test, en mettant la variable PROJ8LIB a nul avant de lancer l'API ne fait plus apparaitre d'erreru lors de l'application de patch. Les COG résultants ont bien un crs..

2021-11-25 08:51 UTC, nlenglet-ign commented
Si la variable PROJ_LIB a une valeur qui ne convient pas, la saisie d'un patch freeze le navigateur de manière très longue (voir infinie) sans explication.
Il faudrait faire apparaître cela dans la fenêtre du navigateur.
Une fois la variable PROJ_LIB à null, pas de soucis constaté, les données patchées contiennent bien SRS et géoréférencement.

2021-11-25 08:52 UTC, nlenglet-ign requested changes
Si la variable PROJ_LIB a une valeur qui ne convient pas, la saisie d'un patch freeze le navigateur de manière très longue (voir infinie) sans explication.
Il faudrait faire apparaître cela dans la fenêtre du navigateur.
Une fois la variable PROJ_LIB à null, pas de soucis constaté, les données patchées contiennent bien SRS et géoréférencement.

2021-11-25 14:57 UTC, amrosu commented
Dans mon cas (docker linux), ça semble bien fonctionner, sans soucis de PROJ_LIB, à NULL par défaut.

2021-11-25 15:02 UTC, nlenglet-ign commented
Pour apporter plus de précisions sur le PROJ_LIB qui est non nul, il provient (pour François et moi), de l'install de Postgis qui ajouter PROJ_LIB en tant que variable d'environnement système.
Mais le problème sera également présent en prod avec une partie des GPAOs historiques qui ajoutaient cette variable (système et/ou utilisateur) à l'installation.

2021-11-30 12:58 UTC, nlenglet-ign reviewed
L'erreur apparaît maintenant clairement dans iTowns quand PROJ_LIB pose soucis.
Est-ce qu'il ne serait pas de notre ressort de s'assurer que cette erreur ne se produit pas puisqu'elle concerne l'environnement de déploiement de l'API ?

2021-11-30 13:37 UTC, gmaillet commented
> 

Je vais ajouter le message d'erreur dans le console côté API mais pour le moment je ne vois pas ce que l'on peut faire de plus?

2021-11-30 14:41 UTC, nlenglet-ign approved these changes
Les messages remontés sont nettement plus parlant.

Il faudrait mettre à jour la doc avec la manip à faire pour résoudre le problème s'il apparaît.

2021-12-01 14:56 UTC, merged