OPI RVB / RVB + IR / IR part 2
ign-packo/PackO pull request #250
Opened 2021-11-29 12:51 UTC by gmaillet

# Motivation

Pouvoir créer un cache avec soit:

- des OPI RVB
- des OPI RVB et IR
- des OPI IR

# Principe

Comme GDAL ne gère pas correctement les COG Jpeg à 4 canaux (le 4ième canal est géré comme un masque binaire), on crée des COG RVB et des COG IR.

Cette PR est la suite de #245 avec les modifications dans l'API et dans iTowns.

2022-01-03 15:05 UTC, amrosu commented
A mettre à jour la doc

2022-01-03 15:06 UTC, gmaillet commented
> 

ok, je m'en charge

2022-01-04 13:05 UTC, ftoromanoff commented
ReadMe
Ligne 55 il manque un 'run' : npm run start-dev

2022-01-05 15:30 UTC, nlenglet-ign requested changes
Pas de remarques sur le code pour ma part (je suis passé très rapidement sur le javascript).
En ce qui concerne le comportement d'un cache sous iTowns, j'ai noté deux choses : 
- la partie concernant les _color layers_ et les _extra layers_ se replie intégralement quand on change la composition colorée que l'on visualise (que cela soit OPIs ou ortho). Cela semble être à corriger que si cela pose des soucis côté utilisateur.
- un bug qui concerne les _extra layers_ et qui est lié au changement de composition colorée. Quand on importe une couche vectorielle supplémentaire et qu'on la supprime par la suite, si on change la composition colorée des OPIs ou des ortho, la couche supprimée réapparaît.

2022-01-06 15:41 UTC, amrosu requested changes
La mise à jour d'un cache RVB avec les images IR et inversement n'est pas géré correctement - à faire

Actuellement : 
- pour un "update" d'un cache IR en ajoutant les images RVB, calcul sans erreur, mais pas correct :
    - dans opi, il semble y avoir les dalles IR et RVB, mais dans ortho - uniquement des IR
    - dans itowns, rien dans la couche RVB ni pour l'ortho, ni pour l'opi dans la vue globale ; dans l'opi, on voit le RVB si on sélectionne une OPI 
  
- pour un update d'un cache RVB avec des IR, le calcul échoue avec message d'erreur "GDALDataset::GetRasterBand(2) - Illegal band"

2022-01-06 16:25 UTC, amrosu requested changes
.

2022-03-09 14:47 UTC, gmaillet commented
> 



> Rebase à faire

rebase fait

2022-03-09 14:48 UTC, gmaillet commented
> La mise à jour d'un cache RVB avec les images IR et inversement n'est pas géré correctement - à faire
> 
> Actuellement :
> 
> * pour un "update" d'un cache IR en ajoutant les images RVB, calcul sans erreur, mais pas correct :
>   
>   * dans opi, il semble y avoir les dalles IR et RVB, mais dans ortho - uniquement des IR
>   * dans itowns, rien dans la couche RVB ni pour l'ortho, ni pour l'opi dans la vue globale ; dans l'opi, on voit le RVB si on sélectionne une OPI
> * pour un update d'un cache RVB avec des IR, le calcul échoue avec message d'erreur "GDALDataset::GetRasterBand(2) - Illegal band"

Pour le moment, il n'est pas autorisé de mélanger les types dans un cache. J'ai ajouté un test dans lors de mise à jour d'un cache.

2022-03-09 14:48 UTC, gmaillet commented
> ReadMe Ligne 55 il manque un 'run' : npm run start-dev

fait

2022-03-09 14:49 UTC, gmaillet commented
> A mettre à jour la doc

fait

2022-03-24 16:19 UTC, nlenglet-ign commented
Deux petites remarques de mon côté : 
- la nomenclature des dalles IR d'ortho : en prenant pour exemple une dalle dont le nom va être AA -> AAi.tif, si on applique un batch sur la branche n, cela devient n_AAi.tif, si on en a un deuxième, n_AA_1i.tif. Je pense qu'il serait peut être plus cohérent de réussir à garder le nom de la dalle tout du long.
- quand on a un cache IR seul, l'affichage sélectionné par défaut sous iTowns est le RGB, ce qui peut donner l'impression qu'il n'y a pas de données.
Ces deux points n'ont rien de bloquant de mon point de vue.

2022-03-24 16:20 UTC, nlenglet-ign approved these changes
Testé de mon côté, je n'ai rien trouvé de bloquant.

2022-03-25 12:46 UTC, amrosu requested changes
Pour les caches IR, après avoir choisi style Ortho = IR et style OPI = IR, la sélection d'OPI ne fonctionne pas correctement  : l'action est faite côté serveur (on voit le nom de l'OPI sélectionnée dans le menu, dans le champ "OPI selected"), mais pas sur la carte.

2022-03-25 12:58 UTC, amrosu commented
Dans le cas où on choisit un style qui n'est pas cohérent avec le cache (le type d'OPI n'existe pas dans le cache), alors il serait bien d'afficher un message en indiquant que le style choisi n'existe pas - actuellement rien n'est mis en place pour ce cas de figure, même pas dans la console du navigateur

2022-04-13 14:33 UTC, gmaillet commented
> Pour les caches IR, après avoir choisi style Ortho = IR et style OPI = IR, la sélection d'OPI ne fonctionne pas correctement : l'action est faite côté serveur (on voit le nom de l'OPI sélectionnée dans le menu, dans le champ "OPI selected"), mais pas sur la carte.

Effectivement, il y avait une faille dans le cas de cache IR au niveau de l'API, c'est corrigé dans gdal_processing.js

> ans le cas où on choisit un style qui n'est pas cohérent avec le cache (le type d'OPI n'existe pas dans le cache), alors il serait bien d'afficher un message en indiquant que le style choisi n'existe pas - actuellement rien n'est mis en place pour ce cas de figure, même pas dans la console du navigateur

J'ai modifié le comportement: maintenant le choix du style ne se fait que sur des compositions colorées valides pour le cache en cours (suivant les cas: RVB ou RVB/IRC/IR ou IR) et par défaut, on affiche au départ un style valide pour le cache (RVB ou IR suivant les cas).

2022-04-20 08:36 UTC, merged