Fix : Ajout couche d'alertes
ign-packo/PackO pull request #260
Opened 2022-01-04 16:03 UTC by ftoromanoff

Corrections de bugs en lien avec la PR permettant l'ajout de couche vecteur.

Fix : 
- bug lors de l'ajout d'une couche vecteur et rafraichissement de la couche d'alerte

Autre :
- Fix d'un bug en lien avec l'upgrade des package webpack

2022-01-06 16:50 UTC, amrosu commented
Mettre à jour la doc : 
- préciser que l'import des vecteurs dans la vue se fait en glissant un vecteur à la fois
- préciser aussi que pour importer un shp, il faut glisser aussi les fichiers dbf, prj, shx

2022-01-10 14:51 UTC, amrosu requested changes
Si on ajoute une nouvelle couche vecteur pendant qu'on traite des alertes (#258), on n'a plus de surlignage résiduel, mais la partie Alerts Layer n'est pas bien gérée : la couche d'alertes sur laquelle on était semble figée et "Validated", "cheched", "comment" disparaissent du menu, c'est comme si on revenait à un état d'origine, mais pas complètement géré - il faudrait mettre Alerts Layer à "-" après un nouveau chargement d'une couche vecteur

2022-01-11 08:45 UTC, ftoromanoff commented
> Mettre à jour la doc :
> 
> * préciser que l'import des vecteurs dans la vue se fait en glissant un vecteur à la fois
> * préciser aussi que pour importer un shp, il faut glisser aussi les fichiers dbf, prj, shx

Fait

2022-01-11 09:25 UTC, ftoromanoff commented
> Si on ajoute une nouvelle couche vecteur pendant qu'on traite des alertes (#258), on n'a plus de surlignage résiduel, mais la partie Alerts Layer n'est pas bien gérée : la couche d'alertes sur laquelle on était semble figée et "Validated", "cheched", "comment" disparaissent du menu, c'est comme si on revenait à un état d'origine, mais pas complètement géré - il faudrait mettre Alerts Layer à "-" après un nouveau chargement d'une couche vecteur

Il y a bien un bug a ce moment la. Mais je me demande si dans le cas ou l'on est déjà en train de travailler sur une couche d'alerte, ne faudrait il pas mieux continuer à avoir cette couche en édition lors de l'ajout d'une nouvelle couche ?
(j'ai fait un commit qui va dans ce sens, mais non forcement final)

2022-01-11 14:39 UTC, amrosu commented
Le bug que j'ai remonté semble bien corrigé et c'est bon aussi pour le maintien de la couche d'alerte en état d'édition lors d'un nouvel import

2022-01-11 14:50 UTC, amrosu requested changes

2022-01-11 14:50 UTC, amrosu commented on itowns/index.js
> +          editing.alertFC.features[0].geometries[editing.featureIndex].properties.comment = value;
Concernant le champ comment, il faudrait garder les corrections pour les mettre dans les couches d'annotations, mais, pour les alertes, ce champ doit être non éditable et il doit contenir uniquement les commentaires déjà existants dans la couche importée et aussi l'adapter pour contenir des phrases (#261).
Comme cette PR s'occupe des corrections qui concernent les alertes, l'évolution du champ comment pour les alertes peut être gérée dans une PR séparée

2022-01-11 14:50 UTC, amrosu commented on README.md
> +POur des soucis d'intégrité, si on desire ajouter plusierus couches, il faut les ajouter une à une.
corriger "POur" -> "Pour", "plusierus" -> plusieurs

2022-01-11 15:19 UTC, ftoromanoff commented on README.md
> +POur des soucis d'intégrité, si on desire ajouter plusierus couches, il faut les ajouter une à une.
> corriger "POur" -> "Pour", "plusierus" -> plusieurs

Corrigé

2022-01-14 09:47 UTC, nlenglet-ign commented
Je confirme que les bugs évoqués dans les tickets #258 et #262 sont bien corrigés sur cette branche.

2022-01-14 14:20 UTC, amrosu approved these changes

2022-01-17 08:15 UTC, merged