Gpao vectorise
ign-packo/PackO pull request #278
Opened 2022-02-14 14:15 UTC by nlenglet-ign

Modification du script vectorise_graph pour permettre de paralléliser la partie qui faisait un goulot d'étranglement en terme de performances (gpao_polygonize en l'occurrence). 
Il y a maintenant deux scripts : 
- prep_vectorise_graph : permet de faire le découpage en tuiles du calcul
- vectorise_graph : permet de créer les lignes de commande et de les insérer dans un JSON compatible GPAOv2
Le readme a été mis à jour en conséquence.

2022-02-15 14:19 UTC, nlenglet-ign commented
Rebase à faire avant merge (sur master et des commits)

2022-02-22 16:11 UTC, amrosu requested changes

2022-02-23 09:21 UTC, nlenglet-ign commented on scripts/vectorise_graph.py
> +    gpkg_path = os.path.join(gpkg_dir, tile_gpkg)
Fait, à venir dans le prochain push

2022-02-23 09:23 UTC, nlenglet-ign commented on scripts/vectorise_graph.py
>          os.remove(gpkg_path)
Fait, à venir dans le prochain push

2022-02-23 09:25 UTC, nlenglet-ign commented on scripts/vectorise_graph.py
> +# debut chantier merge
Fait, à venir dans le prochain push

2022-02-23 09:36 UTC, nlenglet-ign commented on scripts/vectorise_graph.py
> +    print('Cache name = ' + cache_name)
Fait, à venir dans le prochain push

2022-02-23 09:36 UTC, nlenglet-ign commented on scripts/vectorise_graph.py
> +cache_name = os.path.basename(args.output.split('.')[0])
Fait, à venir dans le prochain push

2022-02-23 13:10 UTC, nlenglet-ign commented on README.md
> +                        input data folder
Fait, à venir dans le prochain push

2022-02-23 13:30 UTC, nlenglet-ign commented on README.md
> +                        output file (geopackage format)
Fait, à venir dans le prochain push

2022-02-23 13:44 UTC, nlenglet-ign commented on scripts/prep_vectorise_graph.py
> +    args.input = os.path.abspath(args.input)
Fonctionne correctement, pas de soucis pour ce script

2022-02-23 14:52 UTC, nlenglet-ign commented on scripts/vectorise_graph.py
>      args.input = os.path.abspath(args.input)
Fait, à venir dans le prochain push

2022-02-25 11:58 UTC, amrosu requested changes

2022-02-25 11:58 UTC, amrosu commented on README.md
> +- une première partie pour créer les paramétrages pour les traitements qui sont parallélisables (fichier JSON compatible GPAOv2) : ***prep_vectorise_graphe.py***
GPAOv2 -> service gpao de l'IGN, dans tout le document

2022-02-25 11:58 UTC, amrosu commented on README.md
> +````
Mettre à jour, car n'inclut pas les dernières évolutions

2022-02-25 11:58 UTC, amrosu commented on scripts/prep_vectorise_graph.py
> +    args.input = os.path.abspath(args.input)
Régression par rapport à l'ancien vectorise_graph.py : prep_vectorise_graph ne prend pas en compte les fichiers retouches d'une branche, il reste sur les fichiers d'origine

2022-02-25 12:26 UTC, nlenglet-ign commented on README.md
> +Le résultat du script prep_vectorise_graph.py est un dossier contenant plusieurs VRTs. Un sous-dossier contient les VRTs des dalles prévues pour la deuxième étape du traitement.
Fait.

2022-02-25 12:27 UTC, nlenglet-ign commented on README.md
> +Le résultat final de l'export (après GPAO) est au format GeoPackage.
Fait.

2022-02-25 12:29 UTC, nlenglet-ign commented on README.md
> +- une première partie pour créer les paramétrages pour les traitements qui sont parallélisables (fichier JSON compatible GPAOv2) : ***prep_vectorise_graphe.py***
Fait.

2022-02-25 12:29 UTC, nlenglet-ign commented on README.md
> +````
Fait.

2022-02-25 12:30 UTC, nlenglet-ign commented on README.md
>  Pour le bon fonctionnement du script, il est impératif de mettre la variable d'environnement **GDAL_VRT_ENABLE_PYTHON** à **YES** avant de le lancer.
Fait.

2022-02-28 12:37 UTC, amrosu requested changes

2022-03-07 08:14 UTC, nlenglet-ign commented on README.md
> +Le résultat de ce script est un fichier au format JSON qui est à utiliser pour créer un chantier GPAOv2.
Fait.

2022-03-07 08:15 UTC, nlenglet-ign commented on README.md
> +                        input data folder (created from prep_vectorise_graph.py)
Fait

2022-03-07 08:25 UTC, nlenglet-ign commented on README.md
> +Le script vectorise_graph.py va permettre de créer un fichier json de GPAO (utilisable dans le service gpao de l'IGN).
Fait.

2022-03-07 08:55 UTC, nlenglet-ign commented on README.md
> +Le résultat final du calcul gpao de vectorisation est au format GeoPackage.
Fait

2022-03-07 08:55 UTC, nlenglet-ign commented on README.md
>  - QGISS_CRIPT qui doit pointer vers le répertoire *apps/Python39/Scripts* de QGis. A noter, la version Python peut changer selon la version de QGis utilisée.
Fait

2022-03-07 09:01 UTC, nlenglet-ign commented on README.md
> +Le résultat de ce script est un fichier au format JSON qui est à utiliser pour créer un chantier GPAOv2.
Fait

2022-03-07 09:14 UTC, nlenglet-ign commented on README.md
> +Le résultat du script prep_vectorise_graph.py est un dossier contenant des fichiers nécessaire à l'étape suivant du calcul. Un sous-dossier (./tiles) contient les VRTs des dalles prévues pour la deux
Fait

2022-03-07 10:50 UTC, amrosu approved these changes

2022-03-07 10:50 UTC, amrosu commented on README.md
> +- QGIS_SCRIPT qui doit pointer vers le répertoire *apps/Python39/Scripts* de QGis. A noter, la version Python peut changer selon la version de QGis utilisée.
Ces trois variables sont nécessaires seulement pour Windows, comme tu le précises bien dans la doc, mais dans le code, on voit qu'il n'y a pas de différenciation d'OS, il faudrait la prévoir - évolution à faire en dehors de cette PR

2022-03-07 10:56 UTC, nlenglet-ign commented on README.md
> +- QGIS_SCRIPT qui doit pointer vers le répertoire *apps/Python39/Scripts* de QGis. A noter, la version Python peut changer selon la version de QGis utilisée.
Remarque ajoutée dans l'issue #244 pour futures modifications

2022-03-07 16:30 UTC, ftoromanoff requested changes

2022-03-08 09:01 UTC, ftoromanoff commented on scripts/prep_vectorise_graph.py
> +tiles_dir = os.path.join(args.output, 'tiles')
tiles_dir = os.path.join(os.path.abspath(args.output), 'tiles')

2022-03-08 10:43 UTC, nlenglet-ign commented on README.md
> +  -o OUTPUT, --output OUTPUT
Nécessaire pour avoir un nom de fichier de sortie

2022-03-08 10:43 UTC, nlenglet-ign commented on scripts/prep_vectorise_graph.py
> +tiles_dir = os.path.join(args.output, 'tiles')
Corrigé

2022-03-08 12:56 UTC, nlenglet-ign commented on README.md
> +- une première partie pour créer les paramétrages pour les traitements qui sont parallélisables (fichier JSON compatible avec le service gpao de l'IGN) : ***prep_vectorise_graphe.py***
Typo corrigée

2022-03-08 13:03 UTC, nlenglet-ign commented on README.md
> +- une deuxième partie qui permet d'excécuter tous les traitements parallélisables via le service gpao de l'IGN : ***vectorise_graphe.py***
Basé sur l'exemple de create/update-cache dont les fichiers sont également situés dans le dossier 'scripts'

2022-03-09 07:17 UTC, nlenglet-ign commented on README.md
> +Le résultat du script *prep_vectorise_graph.py* est un dossier contenant des fichiers vrt temporaires et un sous-dossier (./tiles) avec les dalles de graphe nécessaires pour le script *vectorise_grap
L'option est maintenant required

2022-03-09 08:10 UTC, nlenglet-ign commented on README.md
> +````
Pour tout ce qui est doc, il y a déjà eu pas mal de travail dessus avec Ana-Maria, on envisagera des modifications après livraison au SIA

2022-03-09 10:11 UTC, merged