Gestion des erreurs dans le monitor
ign-packo/PackO pull request #304
Opened 2022-04-21 12:10 UTC by ftoromanoff

Gestion des erreurs dans le monitor

Ajout d'un 'event' error.
Emission de l'event lors :
- d'un mauvais nom de branche
- lors d'un DnD non conforme

2022-04-26 08:27 UTC, nlenglet-ign commented
J'ai l'impression que ce ticket concerne les bugs évoqués dans le ticket #227 , est-ce que tu peux confirmer ?

2022-04-26 09:00 UTC, ftoromanoff commented
> J'ai l'impression que ce ticket concerne les bugs évoqués dans le ticket #227 , est-ce que tu peux confirmer ?

Pas exactement, c'est un peu plus général que ça, même si ca permet d'avancer sur le ticket #227.

2022-04-26 12:53 UTC, nlenglet-ign requested changes
Les erreurs sont maintenant signalées par une popup dans le monitor.
Il faut également les récupérer dans la console développeur.

2022-04-26 12:53 UTC, nlenglet-ign commented on itowns/Branch.js
> +    // }
Supprimer le bloc de commentaire

2022-04-26 12:53 UTC, nlenglet-ign commented on itowns/Viewer.js
> +        errors.push(new Error(`Type of file (.${file.name.split('.').pop().toLowerCase()}) not supported.\n`));
Il faudrait également que ces erreurs apparaissent dans la console développeur pour pouvoir être utilisé à des fins de debug.

2022-04-28 12:26 UTC, nlenglet-ign approved these changes

2022-04-28 12:34 UTC, merged