fix(monitor): hide controllers when changing alert layer to an empty layer
ign-packo/PackO pull request #306
Opened 2022-04-22 13:49 UTC by ftoromanoff

Correction d'un bug lors du changement de couche d'alerte d'une couche non vide a une couche vide.
Issue #299

2022-04-25 14:18 UTC, amrosu requested changes

2022-04-25 14:18 UTC, amrosu commented on itowns/Controller.js
> +  resetAlerts(option = { resetIndex: true }) {
Pourquoi le paramètre est un objet et pas juste un bool ?

2022-04-26 08:06 UTC, ftoromanoff commented on itowns/Controller.js
> +  resetAlerts(option = { resetIndex: true }) {
pour plus de lisibilité de code

2022-04-26 12:23 UTC, ftoromanoff commented on itowns/Controller.js
> +  resetAlerts(option = { resetIndex: true }) {
J'ai fait une modification, qui pourrait être satisfaisante.

2022-04-27 07:07 UTC, amrosu approved these changes

2022-04-28 07:42 UTC, merged