Refactorisation: Modification nom variable -> ' -' et cliche
ign-packo/PackO pull request #311
Opened 2022-05-03 14:48 UTC by ftoromanoff

2022-05-10 14:00 UTC, amrosu commented on itowns/Editing.js
> +    this.viewer.message = 'choisir un cliché';
remplacer "cliché" -> "OPI" pour la cohérence, même dans les messages utilisateur

2022-05-10 14:01 UTC, amrosu commented on itowns/Editing.js
> +      this.viewer.message = (this.currentStatus === status.SELECT) ? 'cliché non encore choisi' : 'pas de cliché sélectionné';
idem

2022-05-10 15:00 UTC, ftoromanoff commented on itowns/Editing.js
> +    this.viewer.message = 'choisir un cliché';
C'était pour faire la différence entre français et anglais.
J'ai modifié

2022-05-10 15:00 UTC, ftoromanoff commented on itowns/Editing.js
> +      this.viewer.message = (this.currentStatus === status.SELECT) ? 'cliché non encore choisi' : 'pas de cliché sélectionné';
idem

2022-05-10 15:23 UTC, amrosu requested changes
il reste des 'cliche' à remplacer

2022-05-10 15:24 UTC, amrosu requested changes

2022-05-10 15:24 UTC, amrosu commented on itowns/Editing.js
> +      this.viewer.message = (this.currentStatus === status.SELECT) ? 'Opi non encore choisi' : "pas d'Opi sélectionné";
choisi -> choisie
sélectionné -> sélectionnée

2022-05-16 15:06 UTC, amrosu approved these changes

2022-05-17 07:49 UTC, merged