fetcher GET graph : modification des codes de retour et gestion erreur
ign-packo/PackO pull request #312
Opened 2022-05-04 08:43 UTC by ftoromanoff

2022-05-19 08:44 UTC, amrosu requested changes

2022-05-19 08:44 UTC, amrosu commented on itowns/Editing.js
> +              if (res.status === 201 || res.status === 202) {
mettre code 204 à la place de 201 et 202

2022-05-19 08:44 UTC, amrosu commented on itowns/Editing.js
> +                error.name = 'Erreur BdD ';
BdD -> BD ou "base de données"

2022-05-19 08:44 UTC, amrosu commented on itowns/Editing.js
> +            // 201-> out of graph; 202-> out of bounds; 404-> cache corrompu
204 au lieu de 201/202 - voir plus bas

2022-05-19 08:44 UTC, amrosu commented on middlewares/graph.js
> +    // req.result = { json: { color: [0, 0, 0], opiName: 'out of bounds' }, code: 202 };
supprimer le commentaire

2022-06-07 12:43 UTC, amrosu approved these changes
avant de faire la fusion, corriger :

2022-06-08 09:02 UTC, ftoromanoff commented on doc/swagger.yml
> +          description: No OPI found (cache corrupted)
J'ai fais des recherches et il semblerait que pour un fichier on utilise plutôt "corrupted file" que "corrupt file". https://english.stackexchange.com/questions/269489/for-computer-science-are-the-files-corrupted-or-corrupt
 J'ai donc corrigé par "corrupted cache"

2022-06-08 09:14 UTC, amrosu commented on doc/swagger.yml
> +          description: No OPI found (cache corrupted)
ça marche, tant que tu as corrigé "cache corrupted"
Les deux utilisations ("corrupted file" et "corrupt file") sont correctes, c'est une question de nuance (comme cela est indiqué aussi dans le lien que tu indiques)

2022-06-10 07:30 UTC, ftoromanoff commented
'rebased' effectué. Prêt à être mergé.

2022-06-10 07:34 UTC, merged