refactor(monitor): add new event branch-changed
ign-packo/PackO pull request #313
Opened 2022-05-04 15:17 UTC by ftoromanoff

2022-06-07 13:08 UTC, amrosu requested changes
Regardé très rapidement, une première remarque :

2022-06-07 13:08 UTC, amrosu commented on itowns/Controller.js
> +      if (element === (value === undefined ? this[dropBoxName].getValue() : value)) {
"value" est trop générique

2022-06-10 08:58 UTC, nlenglet-ign approved these changes

2022-06-10 09:52 UTC, amrosu approved these changes

2022-06-13 08:18 UTC, merged