correction scale + coord + mode + color
ign-packo/PackO pull request #32
Opened 2020-10-09 16:16 UTC by gmaillet

Ce n'est pas encore prêt, mais j'ai commencé à gérer:
- l'échelle 
- l'affiche des coord du point
- le mode (select/polygon)
- la couleur du cliché sélectionné
- la touche Echap (pour quitter le mode en cours)

Il reste à faire:
- modifier la forme du curseur suivant le mode

2020-10-19 08:53 UTC, ftoromanoff commented on itowns/Saisie.js
> +    this.message = 'saisir un polygone (Maj pour fermer)';
Je ne mettrais que 'Saisir un polygone" a ce moment la.
et le message 'Maj pour fermer et Esc pour annuler" lors de la saisie (alors que pour le moment ca passe a vide)

2020-10-19 08:54 UTC, ftoromanoff commented on itowns/Saisie.js
> +    if (e.key === "Escape"){
J'ai l'impression qu'une fois que Esc a été appuyer une fois, les lignes rouges de saisie de polygone ne sont plus jamais affichées

2020-10-19 13:38 UTC, gmaillet commented on itowns/Saisie.js
> +    this.message = 'saisir un polygone (Maj pour fermer)';
ok, corrigé dans le prochain commit

2020-10-19 13:39 UTC, gmaillet commented on itowns/Saisie.js
> +    if (e.key === "Escape"){
A priori pas de bug à ce niveau, par contre il est vrai qu'il y a parfois un problème avec l'affichage du polygone (je crois que cela se produit lorsqu'on commence une saisie alors que la vue est en cours de rafraichissement). Je pense que le bug était déjà présent dans les versions antérieures et n'a pas de lien avec cette PR

2020-10-20 14:52 UTC, gmaillet commented
Todo:
- bloquer la saisie de polygone et le select tant qu'un patch est en cours de traitement
- message: calcul en cours

2020-10-21 07:40 UTC, amrosu commented
Dans le cas Zoom-Dezoom pendant un traitement, on a ce type de message : 
![Capture du 2020-10-21 09-18-56](https://user-images.githubusercontent.com/24602370/96688349-5d2ef700-1381-11eb-8648-75cf103732ae.png)

2020-10-23 07:29 UTC, ftoromanoff commented on itowns/index.html
> +        var placement = {
A supprimer (pb lors du rebase)

2020-10-23 07:45 UTC, ftoromanoff commented on itowns/index.html
> +        var placement = {
Fait

2020-10-23 08:39 UTC, ftoromanoff requested changes

2020-10-23 08:39 UTC, ftoromanoff commented on itowns/Saisie.js
> +    this.message = "calcul en cours";
le message s'efface des que l'on fait un click (même si le calcul n'est pas fini)

2020-10-23 08:39 UTC, ftoromanoff commented on itowns/index.html
> +            myControl.updateMouseCursorType = function updateMouseCursorType() {
le clique molette change le curseur en "travail en cours" mais ne revient pas a la normal a la fin du deplacement

2020-10-23 08:39 UTC, ftoromanoff commented on itowns/Saisie.js
> +    }
il y a deux fois :
keypress(e) {
...
}
Pb dans le rebase ? quelles lignes garder.

2020-10-23 08:42 UTC, ftoromanoff commented on itowns/Saisie.js
> +    this.currentStatus = status.EN_COURS;
je ne suis pas sur a 100% que cela fonctionne.
j'ai l'impression qu'apres un long calcul le refresh est toujours bloqué meme apres avoir reçu une reponse du serveur (possiblement tant que l'on ne le fais pas manuellement)

2020-10-23 14:07 UTC, gmaillet commented
@ftoromanoff et @amrosu : j'ai fait plusieurs corrections en prenant en compte les remarques de François et quelques améliorations:
- suivant le mode actif (select ou polygon): le menu change de couleur
- la couleur de fond du menu/cliche change en fonction du cliché sélectionné
- le curseur passe en mode "wait" pendant les traitements (patch, undo, redo ou clear)

2020-10-23 14:25 UTC, ftoromanoff commented
Il ne faudrait pas afficher le dernier point (quand maj est appuyé) du polygone lors de la création d'un polygone pour la saisie

2020-10-23 15:55 UTC, gmaillet commented
Prise en compte de la remarque de @ftoromanoff pour que le dernier point ne soit pas pris en compte lorsque l'on appuie sur Maj.

2020-10-26 12:21 UTC, ftoromanoff approved these changes

2020-10-26 16:40 UTC, amrosu requested changes

2020-10-26 16:40 UTC, amrosu commented on itowns/index.html
> +            }
L'échelle ne semble pas être correcte - j'ai vérifié par rapport au Géoportail et j'obtiens des différences non négligeables (un exemple dans captures d'écran plus bas)
![Capture d’écran 2020-10-26 à 16 45 35](https://user-images.githubusercontent.com/24602370/97197534-0d4f9600-17ae-11eb-8232-a5e3e948b374.png)
![Capture d’écran 2020-10-26 à 17 07 17](https://user-images.githubusercontent.com/24602370/97197561-150f3a80-17ae-11eb-8ee9-5858b8675c28.png)

2020-10-26 16:40 UTC, amrosu commented on itowns/index.html
> +            }
En zoomant et dézoomant, j'ai des valeurs aberrantes pour l'échelle : je peux passer de 20 km à 58857.39 km en un coup de dezoom ou de 0.14 cm à 5904.93 km en un coup de zoom et parfois il n'arrive plus à se retrouver, il reste bloqué sur la valeur aberrante et mes zoom-dezoom restent sans effets sur l'affichage 

Et j'ai l'impression aussi qu'il n'y pas vraiment de limites dans les zoom ou dezoom, il serait bien d'en ajouter

2020-10-26 16:46 UTC, amrosu commented
Quand on clique en dehors de l'emprise graphe, dans "cliche" on a bien le message "out of bounds", mais l'OPI sélectionnée auparavant reste affichée, alors qu'on devrait ne rien avoir comme OPI
![Capture d’écran 2020-10-26 à 17 29 38](https://user-images.githubusercontent.com/24602370/97199960-e8a8ed80-17b0-11eb-8964-88cb646fde5c.png)

2020-10-27 14:49 UTC, amrosu commented on itowns/index.html
> +            }
En attendant la correction de la fonctionnalité "Scale", j'ai mis en commentaire les lignes de code correspondantes et j'ai fait un ticket dédié (#43 )

2020-10-28 12:39 UTC, ftoromanoff commented
Nouveau petit bug :
Un clique long de déplacement est considéré comme un clique alors que ca ne devrait pas.
(lors du select ou de la création de polygone)

2020-10-28 14:19 UTC, amrosu commented
Et un autre bug lié à "select" : si on clique sur select après avoir déjà une OPI sélectionnée, le champ "cliche" est vidé et dans le champ "message" contient "choisir un cliche", mais l'OPI sélectionnée auparavant reste mise en évidence
Ce qu'on faudrait faire si on a une OPI et on refait select :  mettre dans message "choisir un clichée +  laisser l'OPI sélectionnée auparavant active + le champ "cliche" rempli avec le nom de cette OPI et le modifier uniquement après clique sur une nouvelle OPI

2020-10-30 15:55 UTC, amrosu commented
Ce PR commence à être complexe et donc des tickets ont été rédigés avec les demandes de correction / évolution et traités par la suite

2020-10-30 15:56 UTC, merged