feat(monitor,API): change wmtsStyle for Graph layer
ign-packo/PackO pull request #326
Opened 2022-06-24 14:40 UTC by ftoromanoff

En lien avec le ticket [RedMine#2075](http://redmine.forge-idi.ign.fr/issues/2075)

2022-07-01 08:29 UTC, nlenglet-ign requested changes
Pas de soucis au niveau des modifications dans le code.

Il y a des soucis sous iTowns :
- quand on ouvre le navigateur, je tombe actuellement sur un fond bleu uniforme, si je change de la couche Ortho, le soucis disparaît (il réapparaît avec un F5)
- la couche contour n'apparaît plus, quelque soit le niveau de zoom 
Testé sous Edge

2022-07-01 08:54 UTC, nlenglet-ign approved these changes
Pas de soucis constaté lors des tests sous iTowns et QGis

2022-07-05 12:24 UTC, amrosu approved these changes
A gérer la régression décrite dans #329

2022-07-05 12:25 UTC, amrosu requested changes
A gérer la régression décrite dans #329

2022-07-12 06:25 UTC, nlenglet-ign requested changes
Quand on charge un cache IR seul, les couches OPI et ortho apparaissent correctement.
Par contre, la couche contour n'est plus visible.

2022-07-12 14:15 UTC, ftoromanoff commented
> Quand on charge un cache IR seul, les couches OPI et ortho apparaissent correctement. Par contre, la couche contour n'est plus visible.

Corrigé

2022-07-13 12:01 UTC, nlenglet-ign approved these changes

2022-07-21 08:07 UTC, amrosu approved these changes
Testé rapidement et cela semble fonctionner. Mais je constate des problèmes importants de performances du client lors du travail avec des vecteurs (vue figée, voir #270), problèmes qui semblent être augmentés sur cette branche - à traiter dans une autre PR

2022-07-21 08:07 UTC, merged