Undo redo 2
ign-packo/PackO pull request #33
Opened 2020-10-15 14:52 UTC by ftoromanoff

Branche pour la gestion des undo/redo
Modifications apportées : 
- nom du cache a utilisé en argument (ex --cache cache_test)
- PORT et SERVER en argument (ex --server localhost --port 8081)

- creation du fichier routes/patch (et test/patch)
   => route POST /graph/patch déplacée en POST /patch
   => ajout des routes GET /patchs, PUT /patch/undo, PUT /patch/redo etPUT /patchs/ clear

- modification interface itowns : ajout d'une fenêtre message (en lien avec les opérations undo/redo)

2020-10-16 08:26 UTC, amrosu commented
J'ai commencé la révision

2020-10-16 13:04 UTC, gmaillet approved these changes
deux petites remarques, mais globalement c'est bon pour moi. J'ai testé des cas un peu tordus (genre redémarrage du serveur, annulation/redo/clear dans tous les sens): je n'ai trouvé aucun problème.

2020-10-16 13:04 UTC, gmaillet commented on routes/patch.js
> +    if (outOfBoundsTiles.length) {
c'est sans doute là que le comportement est discute: faut-il considérer que c'est une erreur ou faut-il patcher ce que l'on peut?

2020-10-16 13:17 UTC, ftoromanoff commented on test/patch.js
> +  */
fait

2020-10-19 12:10 UTC, amrosu requested changes
Il y a des problèmes avec les saisies et avec la prise en compte d'un port autre que celui par défaut

2020-10-19 12:10 UTC, amrosu commented on test/patch.js
> +          res.text.should.equal('redo 1 succeed');
corriger "succeed" -> "succeeded" ou plus simple "OK"

2020-10-19 12:10 UTC, amrosu commented on test/patch.js
> +          res.text.should.equal('clear succeed');
idem "succeed"

2020-10-19 15:08 UTC, ftoromanoff commented on serveur.js
> +  const PORT = argv.port ? argv.port : 8081;
j'ai créé une nouvelle branche pour résoudre ce problème : GestionPORT

2020-10-19 15:13 UTC, ftoromanoff commented on itowns/Saisie.js
>      console.log('saisir d un polygon');
j'ai changé le message par 'saisie d un polygone'

2020-10-19 15:14 UTC, ftoromanoff commented on itowns/Saisie.js
> +          this.message = "Polygon: out of OPI bounds"
message modifié.
Pour ton erreur je pense qu'il faudrait que je regarde ca avec toi sur tes données. Je n'ai pas réussi a faire apparaitre cette erreur chez moi...

2020-10-19 15:15 UTC, ftoromanoff commented on test/patch.js
> +          res.text.should.equal('redo 1 succeed');
message modifié par : 'redo: patch ${numPatch} reapplied'

2020-10-19 15:21 UTC, ftoromanoff commented on test/patch.js
> +          res.text.should.equal('clear succeed');
message modifié par : 'clear: all patch(es) deleted'

2020-10-21 08:32 UTC, amrosu commented on itowns/Saisie.js
> +          this.message = "Polygon: out of OPI bounds"
bug difficile à reproduire, probablement lié à d'autres bugs corrigés ou à corriger, notamment dans l'IHM, à voir sur la PR de la branche reworkItowns

2020-10-21 08:36 UTC, amrosu commented on test/patch.js
> +          res.text.should.equal('clear succeed');
à enlever la parenthèse car inutile

2020-10-21 08:38 UTC, amrosu commented on itowns/Saisie.js
>      console.log('saisir d un polygon');
à enlever "d un" et laisser "saisie polygone" ou échapper l'apostrophe

2020-10-21 08:43 UTC, amrosu commented on itowns/Saisie.js
> +          this.message = "Polygon: out of OPI bounds"
petite remarque : pour le message, on peut enlever ":" pour pouvoir afficher le message en entier

2020-10-21 08:58 UTC, ftoromanoff commented on test/patch.js
> +          res.text.should.equal('clear succeed');
fait

2020-10-21 08:59 UTC, ftoromanoff commented on itowns/Saisie.js
> +          this.message = "Polygon: out of OPI bounds"
j'ai enlevé la majuscule à 'Polygon' pour libérer un peu de place (on voit un demi 's' maintenant ^^)

2020-10-21 09:00 UTC, ftoromanoff commented on itowns/Saisie.js
>      console.log('saisir d un polygon');
j'ai rajouté l'apostrophe

2020-10-21 09:15 UTC, amrosu approved these changes

2020-10-21 09:39 UTC, merged