Rework test
ign-packo/PackO pull request #337
Opened 2022-07-21 07:58 UTC by ftoromanoff

2022-09-01 09:45 UTC, amrosu commented
Utiliser cache_test et ne pas reproduire un nouveau cache (supprimer, sur le dépôt aussi, le cache_regress  qui a été recopié dans cette branche dans data/)

2022-09-06 10:16 UTC, ftoromanoff commented
En attente de la PR de Nathan sur les tests unitaires de création de cache

2022-12-01 14:38 UTC, amrosu requested changes

2022-12-01 14:38 UTC, amrosu commented on regress/test-API/2_cache.js
> +    // });
à voir si on doit garder ce test

2022-12-01 14:38 UTC, amrosu commented on regress/test-API/4_vector.js
> +    describe('Vector valid: vector_example', () => {
'vector valid' -> 'valid vector'

2022-12-01 14:38 UTC, amrosu commented on regress/test-API/4_vector.js
> +    describe('Vector non valid', () => {
'Vector non valid' -> 'Non valid vector'

2022-12-01 14:38 UTC, amrosu commented on regress/test-API/4_vector.js
> +    describe('idRemarksVector non valid', () => {
idem

2022-12-01 14:38 UTC, amrosu commented on regress/test-API/4_vector.js
> +    describe('idFeature non valid', () => {
idem

2022-12-01 14:38 UTC, amrosu commented on regress/test-API/4_vector.js
> +    describe('idRemarksVector non valid', () => {
idem

2022-12-01 14:38 UTC, amrosu commented on routes/patch.js
> +  // branch.getCachePath,
à nettoyer

2022-12-01 14:38 UTC, amrosu commented on routes/vector.js
> +  // branch.getCachePath,
idem

2022-12-01 14:38 UTC, amrosu commented on regress/test-API/3_branch.js
> +    describe('rebase a branch on a branch on aonther cache', () => {
"on aonther" -> "of another"

2022-12-02 10:27 UTC, ftoromanoff commented on middlewares/wmts.js
> +    // let style;
fait

2022-12-02 10:27 UTC, ftoromanoff commented on middlewares/wmts.js
> +    // }
fait

2022-12-02 10:28 UTC, ftoromanoff commented on regress/test-API/4_vector.js
> +    describe('Vector valid: vector_example', () => {
corrigé

2022-12-02 10:28 UTC, ftoromanoff commented on regress/test-API/4_vector.js
> +    describe('Vector non valid', () => {
corrigé

2022-12-02 10:28 UTC, ftoromanoff commented on regress/test-API/4_vector.js
> +    describe('idRemarksVector non valid', () => {
corrigé

2022-12-02 10:28 UTC, ftoromanoff commented on regress/test-API/4_vector.js
> +    describe('idRemarksVector non valid', () => {
corrigé

2022-12-02 10:28 UTC, ftoromanoff commented on routes/patch.js
> +  // branch.getCachePath,
fait

2022-12-02 10:28 UTC, ftoromanoff commented on routes/vector.js
> +  // branch.getCachePath,
fait

2022-12-02 10:28 UTC, ftoromanoff commented on regress/test-API/3_branch.js
> +    describe('rebase a branch on a branch on aonther cache', () => {
corrigé

2022-12-02 10:28 UTC, ftoromanoff commented on regress/test-API/2_cache.js
> +    // });
gardé en ajoutant un ligne de commentaire

2022-12-02 14:17 UTC, amrosu approved these changes

2022-12-05 08:58 UTC, merged