fix(API): COG levels
ign-packo/PackO pull request #351
Opened 2022-09-27 15:05 UTC by nlenglet-ign

2022-10-06 14:39 UTC, amrosu requested changes

2022-10-06 14:39 UTC, amrosu commented on cog_path.js
> +  const levelCOG = levelMax - Math.floor((levelMax - level) / nbLvlInCOG) * nbLvlInCOG;
La correction sur levelCOG fonctionne bien pour différentes tailles de dalle (16x16, 8x8, 4x4) si la taille des tuiles est 256x256, mais pas tout à fait sur des tuiles différentes de 256 (ex: 512 ou 1024). Cela semble être lié à la valeur de 'level' (Z) pas correcte : exemple :
- pour cache avec *tuiles 512x512 et dalles 16x16*, résolution 20 cm : pour DeZoom 1/32, il affiche en fait level=15 (donc DeZoom=1/16), au lieu de level=14 (2ème COG), et donc levelCOG=19 - 1er COG
- pour cache avec *tuiles 1024x1024 et dalles 16x16*, résolution 20 cm : pour DeZoom 1/32, il affiche level=16 (donc DeZoom=1/8), au lieu de level=14 (2ème COG), et donc levelCOG=19 - 1er COG

Il semble donc y avoir un décalage entre le 'level' (et donc le 'levelCOG') demandé et celui affiché si la tuile est différente de 256.

2022-10-06 14:53 UTC, amrosu commented
Et petit commentaire, en dehors de cette PR : actuellement, dans le client itowns, le niveau maximal d'affichage du graphe/contour et de saisie est lié à la taille de la dalle (ex: Dezoom 1/16 pour dalles de 16x16, 1/8 pour 8x8 et 1/4 pour 4x4). (L'affichage actuel dans itowns du graphe/contour est 'décalé' pour des caches avec des tuiles différentes de 256x256, voir plus haut, avec des incohérences avec le message 'Graph not displayed' qui n'est pas dépendant de 'level'.)

A voir avec l'utilisateur final si, pour ses besoins d'affichage avec itowns, on doit faire évoluer le client itowns, en imposant 1/16 comme niveau max pour graphe/contour et pour les saisies, indépendamment de la taille de la dalle

2022-10-10 09:21 UTC, gmaillet commented on cog_path.js
> +  const levelCOG = levelMax - Math.floor((levelMax - level) / nbLvlInCOG) * nbLvlInCOG;
Je n'ai pas trop compris ce commentaire, mais je ne suis pas convaincu que le problème signalé concerne la modification proposée (la taille de tuile n'intervient pas dans cette partie du code).
En pratique, j'ai testé différents caches:
Avec du 512x8x8, il considère bien qu'il y a 4 niveaux par COG (8x8 à pleine résolution, 4x4 en ssech 2, 2x2 en ssech 4 et 1 en ssech 8 );

- pour une requête de niveau 20, il travaille bien en sous-ech 2 du COG de niveau 21
- pour une requête de niveau 15, il travaille bien en sous-ech 4 du COG de niveau 17
- etc

j'ai testé du 1024x4x4, du 256x16x16 et du 512x8x8 sans constater de problème.
Est-ce que le problème signalé n'est pas plutôt dans la gestion WMTS d'iTowns?

2022-10-11 13:01 UTC, amrosu commented on cog_path.js
> +  const levelCOG = levelMax - Math.floor((levelMax - level) / nbLvlInCOG) * nbLvlInCOG;
Il y a un problème avec 'level' qui intervient bien dans la modification proposée. Il est fort probable que cela soit plutôt lié à gestion WMTS d'itowns, la visualisation des caches est entre autres impactée, avec des graphes/contours qui semblent affichés au-delà de niveaux max (maxGraphDezoom) - voir aussi le commentaire plus bas.

Si cela touche que le client itowns, dont nous avons dit qu'on le gardera en l'état si remplacé par QGIS :
- faut-il corriger l'éventuel problème de 'décalage' de 'level' qui fait que les graphes/contours semblent affichés au-delà de niveaux max ?
- - pour les besoins de la visualisation des caches, doit-on faire évoluer le client itowns, en imposant 1/16 comme niveau max pour graphe/contour et pour les saisies ?

2022-10-14 12:30 UTC, gmaillet commented
La correction proposée ne règle effectivement pas les problèmes liés à iTowns mais offre déjà une amélioration notable (en particulier dans le contexte QGis) et ces corrections liées à iTowns peuvent être mises en attente parce que:

- il n'est pas acté que l'on utilisera effectivement des caches avec des tuiles d'une autre dimension que 256
- on a décidé de ne plus faire d'évolutions lourdes sur la partie iTowns pour l'instant

éventuellement, on peut le noter dans la doc pour ne pas l'oublier.

2022-10-20 12:00 UTC, gmaillet approved these changes
RAS

2022-10-20 13:46 UTC, amrosu approved these changes

2022-10-20 13:49 UTC, merged