feat(cache): allow no mtd to create cache
ign-packo/PackO pull request #366
Opened 2022-11-17 08:01 UTC by nlenglet-ign

Pouvoir autoriser la création d'un cache sans métadonnées présentes dans le graphe en entrée.
Cf. issue #365 pour plus de détails

2022-11-23 13:45 UTC, amrosu requested changes
L'option '-z' n'est pas fonctionnelle en l'état, à cause du "bool"  - voir explication plus bas -> à remplacer avec "int" et faire les adaptations et tests nécessaires

2022-11-23 13:45 UTC, amrosu commented on scripts/cache.py
> +                        default=False)
Il n'est pas recommandé d'utilisé 'bool' car il transforme une chaîne vide en 'False' et une non-vide (même 0 ou 'False') en 'True'.
Il faut mettre type=int pour l'option '-z', avec une valeur par défaut (par exemple  0) et ajouter une explication pour l'utilisateur

2022-11-23 14:11 UTC, amrosu requested changes
Et il serait bien d'ajouter un commentaire dans le code sur la signification de 'NA'.

Et dans la doc, il faudrait peut-être aussi dire que dans le cas "sans métadonnées", elles seront mises à "NA" et donner la signification

2022-11-24 10:10 UTC, nlenglet-ign commented on README.md
> +                        GeoPackage filename or connection string ("PG:host=localhost
Fait

2022-11-24 10:10 UTC, nlenglet-ign commented on scripts/cache.py
> +                        default=False)
Le type de l'option a été changé à int (et les adaptations nécessaires faites)

2022-11-24 10:11 UTC, nlenglet-ign commented
> Et il serait bien d'ajouter un commentaire dans le code sur la signification de 'NA'.
> 
> Et dans la doc, il faudrait peut-être aussi dire que dans le cas "sans métadonnées", elles seront mises à "NA" et donner la signification

Mise à jour de la doc faite pour répondre à cette demande.

2022-11-24 13:04 UTC, amrosu requested changes

2022-11-25 10:26 UTC, amrosu requested changes

2022-11-25 10:26 UTC, amrosu commented on scripts/cache.py
> +            if args.zeromtd > 0:
Le cas pour les valeur négatives n'est pas géré, il faut l'inclure dans la condition (pour update aussi)

2022-11-25 15:12 UTC, nlenglet-ign commented on scripts/cache.py
> +                        default=False)
Vu

2022-11-25 15:14 UTC, nlenglet-ign commented on scripts/cache.py
> +                        default=0)
Signification de la valeur par défaut ajoutée

2022-11-25 15:14 UTC, nlenglet-ign commented on scripts/cache.py
> +                        help="allow input graph with no metadata (default : 0)",
Corrigé

2022-11-25 15:14 UTC, nlenglet-ign commented on scripts/cache.py
> +            if args.zeromtd > 0:
Cas géré.

2022-11-29 16:37 UTC, amrosu requested changes

2022-11-29 16:37 UTC, amrosu commented on scripts/cache.py
> +                    time_ut = opi_feature.GetField('HEURE_TU')
Dans le cas où on demande les métadonnées (-z=0), il faudrait vérifier que le graphe contient bien toutes les mtd et qu'elles sont aux formats attendus, et attraper l'erreur sinon

2022-12-01 08:00 UTC, amrosu requested changes
La mise en base des caches sans métadonnées ne fonctionne pas, "NA" n'est pas compatible avec ce qui est attendu dans la base

2022-12-19 15:01 UTC, amrosu reviewed
J'ai poussé quelques commits : correction du systemExit (d15e728), ajout de la vérification que les mtd ne sont pas vides (b5b2b2) et refactorisation du code avec création d'une fonction pour la vérification des métadonnées (313fe58). Je te laisse regarder

2022-12-20 12:55 UTC, nlenglet-ign commented
Pas de soucis constaté suite au refactoring, ça me semble très bien comme ça.

2022-12-20 13:22 UTC, amrosu approved these changes
Validation de la PR avec quelques remarques :
- il y a encore quelques tests (combinaison create/update) à ajouter dans les tests de non-régression du cache -  je vais mettre une liste dans  #345 et cela peut être traité ultérieurement
- pour "update", si on travaille plusieurs fois sur la même OPI, ses métadonnées sont mises à jour que la 1ère fois - ce fonctionnement est peut-être devenu obsolète suite à l'ajout de l'option -z ; à modifier si l'utilisateur le demande, en fonction de ses besoins

2022-12-20 14:00 UTC, merged