Gestion port
ign-packo/PackO pull request #39
Opened 2020-10-21 11:29 UTC by ftoromanoff

1) Gestion du 'port' et du 'server' de manière dynamique : pour l'API, le swagger et itowns
2) Ajout d'une aide pour l'API (serveur.js --help)

Modification : Suppresion du '\' final dans l'url de l'API dans itowns

2020-10-21 14:54 UTC, amrosu requested changes

2020-10-21 14:54 UTC, amrosu commented on serveur.js
>    const SERVER = argv.server ? argv.server : os.hostname();
ça ne fonctionne pas si on utilise docker car conflit entre id conteneur et localhost et dans swagger, pour toutes les requêtes j'ai  : 
Server response
Code | Details
-- | --
Undocumented | TypeError: Failed to fetch

2020-10-21 14:54 UTC, amrosu commented on serveur.js
> +  .help();
ajouter option "-h"

2020-10-21 14:54 UTC, amrosu commented on itowns/index.html
> +        const port = urlParams.get('port') ? urlParams.get('port') : 8081;
modifier nom variables -> serverAPI, portAPI

2020-10-21 15:04 UTC, amrosu commented on serveur.js
>    const SERVER = argv.server ? argv.server : os.hostname();
ça fonctionne si on ajoute "-h hostname" quand on lance le docker

2020-10-21 15:24 UTC, amrosu commented on serveur.js
> +  .help();
ça fonctionne si on ajoute "-h hostname" lors du lancement du docker

2020-10-21 15:37 UTC, ftoromanoff commented on itowns/index.html
> +        const port = urlParams.get('port') ? urlParams.get('port') : 8081;
fait
par contre dans l'url itowns il ne faut pas mettre les majuscule

2020-10-22 07:36 UTC, amrosu requested changes

2020-10-22 07:36 UTC, amrosu commented on itowns/index.html
> +        const port = urlParams.get('port') ? urlParams.get('port') : 8081;
Pour l'adresse de la requête, il faut renvoyer un message si il n'arrive pas à la joindre (mauvais portapi ou serveurapi ou l'url en général...), un message visible pour l'utilisateur - type "Page non-accessible"

2020-10-22 12:01 UTC, amrosu commented on itowns/index.html
> +            prompt(`API non accessible a l'adresse renseignée (${apiUrl}). Veuillez entrer une adresse valide :`, apiUrl)
ça fonctionne bien, mais petite remarque: à corriger "a l'adresse" -> "à l'adresse"

2020-10-22 12:10 UTC, amrosu approved these changes

2020-10-22 12:11 UTC, merged