Refactor projection
ign-packo/PackO pull request #403
Opened 2023-07-20 15:19 UTC by nlenglet-ign

Ajout des projections nécessaires à l'utilisation en production
Mise à jour des paramètres par défaut (256*16 -> 512*8)
Mise à jour swagger en correspondance

2023-08-03 13:36 UTC, amrosu requested changes
Il manque la mise mise à jour de l'aide pour create_cache, notamment la valeur par défaut pour le param "overviews" qui fait référence à LAMB93_5cm.json qui n'existe plus.
Il faut aussi aussi à jour la doc README

2023-10-05 08:05 UTC, amrosu requested changes
Il faudrait assurer la rétrocompatibilité LAMB93 <-> RGF93_LA93, notamment pour permettre de continuer sur des caches créés avant le changement et qui contiennent donc la "vielle" nomenclature *LAMB93*.

Dans la base de données, comme on enregistre le crs avec code EPSG, ça devrait être bon, pas d'impact suite au changement

2023-11-14 08:08 UTC, nlenglet-ign commented
Tests réalisées pour la rétrocompatibilité LAMB93 <-> RGF93_LA93 : 
- itowns OK (vérifier avec plus de logs)
- export vue QGis OK (test saisie à faire)
- soucis lors de requêtes WMTS de type GetTile / GetFeatureInfo

2023-11-17 13:41 UTC, amrosu commented
Le problème ave GetTile/GetFeatureInfo dans la doc vient de TILEMATRIXSET qui est sur la forme d'une liste contenant les **nouveaux** identifiants de la pyramide (et donc pas compatible avec les vieux cache contenant les **vieux** identifiants). Pour corriger cela, je propose de passer à un champ libre - commit [4d92df7](https://github.com/ign-packo/PackO/pull/403/commits/4d92df72144fccba22fd0c5a7309d4969daf9c1f).
J'ai également corrigé une petite coquille dans l'exemple POST/ cache - commit [9c93ff4](https://github.com/ign-packo/PackO/pull/403/commits/9c93ff4acc8d42438c3b2a2d37b7a61387a6faac)

2023-11-21 07:06 UTC, nlenglet-ign commented
Les saisies sont OK sous QGis.
Le comportement attendu dans swagger est le bon également.

2024-06-26 15:17 UTC, amrosu commented
J'ai remplacé les LAMB93->RGF93_LA93 restants dans la doc et les fichiers des tests regress, plus rebase de la branche

2024-07-02 13:21 UTC, amrosu commented
Et pour info, le repère géodésique pour Mayotte changera bientôt selon le service de géodésie de l'IGN : RGM23 remplacera RGM04. Pour le moment, RGM23 n'est pas officielle, donc pas de code EPSG, ni de définition d'emprise ... D'ici-là, on gardera RGM04 pour Mayotte

2024-07-02 13:22 UTC, amrosu approved these changes

2024-10-04 12:19 UTC, gmaillet approved these changes
Validé, à merger

2024-10-07 06:59 UTC, merged