optimisation + correction sur les patchs
ign-packo/PackO pull request #55
Opened 2020-11-06 12:30 UTC by gmaillet

- optimisation: on vérifie pour chaque tuile s'il y a un pixel modifié plutôt que de se baser uniquement sur la BBox du patch
- correction: dans certain cas, il y a un pixel parasite en (0, 0), en particulier sur le patch n'est pas sur la tuile. On ajoute donc une ligne au masque pour être plus robuste

2020-11-06 12:59 UTC, gmaillet commented
@amrosu @ftoromanoff je n'arrive pas à reproduire l'erreur signalé sur l'intégration continue de GitHub chez moi, pouvez-vous faire un test?

2020-11-06 13:06 UTC, gmaillet commented
@ftoromanoff @amrosu c'est bon, le test passe, c'était effectivement une erreur que je ne pouvois pas voir parce que mon cache local n'était pas totalement remis à zéro (il restait les fichiers non versionnés par git)

2020-11-06 16:04 UTC, ftoromanoff requested changes

2020-11-06 16:28 UTC, ftoromanoff approved these changes

2020-11-06 16:35 UTC, amrosu approved these changes

2020-11-06 16:39 UTC, ftoromanoff reviewed
De ce que je vois tu testes a chaque fois si des fichiers liées a un patch en particulier existent qui sont des tests fs.existsSync().
Dans le cas d'un patch pour lequel BBox = tuiles impactées, le traitement devraient être allongé.
Et un temps de traitemetn reduit devrait être retrouvé sur les saisies particulières pour lesquelles BBox != tuiles à modifiées (ou en bordure de tuiles)
Il faudrait peut être testé en conditions de production ?

2020-11-09 07:41 UTC, gmaillet commented
Il y avait encore des failles possibles parce qu'on ne supprime pas systématiquement les ortho_n.png lorsqu'on fait des undo (normale puisqu'on a la possibilité de faire des redo) et comme on réutilise les patchId qui ne sont plus utiles on peut se retrouver avec des images parasites lors d'un redo.
Proposition de solution: on stocke la liste des tuiles impactées pour chaque patch (en plus ça évite de refaire une analyse et /ou des tests d'existence de fichier).

2020-11-09 12:58 UTC, merged

2020-11-09 13:54 UTC, amrosu commented
Avant, si on faisait des undo/redo, ces actions touchaient uniquement les saisies contenues dans l'OPI sélectionnée - avec l'avantage qu'on ne pouvait pas agir sur une autre zone la zone active / visible pour l'utilisateur au moment de l'action undo/redo 
Maintenant, je vois que ces actions sont effectuées indifféremment de l'OPI sélectionnée