Create cache multi
ign-packo/PackO pull request #60
Opened 2020-11-12 12:46 UTC by ftoromanoff

Modification du script python de création du cache.

- Séparation du process en 2 étapes distinctes : 
   - Découpage en tuile, image par image
   - Génération de l'ortho et du graph, tuile par tuile

- Chacune des étapes est ensuite multiprocessée en utilisant le max des CPU disponible - 1

Sur mon PC, le calcul du cache sur 31 OPI a pris 1h05 en utilisant 7 CPU contre 2h45 dans la version précédente

2020-11-12 17:18 UTC, amrosu requested changes
Je n'ai pas encore fait des tests, mais voici mes premières remarques sur le code

2020-11-12 17:18 UTC, amrosu commented on scripts/createCache.py
> +    ecriture = False
tous les noms des variables, sauf celui-ci, sont en anglais -> à mettre en anglais

2020-11-13 08:00 UTC, gmaillet commented on scripts/createCache.py
> +    target_ds = gdal.GetDriverByName('MEM').Create('', tileSize, tileSize, 3, gdal.GDT_Byte)
Pas de problème pour moi: la taille est variable mais on sera toujours sur des dalles carrées

2020-11-13 08:31 UTC, amrosu commented
Il faudrait ajouter une barre d'avancement pour chaque processus, notamment pour ceux qui sont très long

2020-11-13 08:39 UTC, ftoromanoff commented on scripts/createCache.py
> +    target_ds = gdal.GetDriverByName('MEM').Create('', tileSize, tileSize, 3, gdal.GDT_Byte)
Mettre un tuple était mon idée de base, mais j'avais simplifier pour les tests. J'ai oublié de corriger...

2020-11-13 09:47 UTC, ftoromanoff commented on scripts/createCache.py
> +# os.environ['PROJ_LIB'] = 'C:\\Users\\ftoromanoff\\AppData\\Local\\Programs\\Python\\Python37-32\\Lib\\site-packages\\osgeo\\data\\proj'
Fait

2020-11-13 09:47 UTC, ftoromanoff commented on scripts/createCache.py
> +    target_ds = gdal.GetDriverByName('MEM').Create('', tileSize, tileSize, 3, gdal.GDT_Byte)
Fait

2020-11-13 09:47 UTC, ftoromanoff commented on scripts/createCache.py
> +    target_ds = gdal.GetDriverByName('MEM').Create('', tileSize, tileSize, 3, gdal.GDT_Byte)
Fait,
c'est une variable définie au début du programme pour le moment

2020-11-13 09:48 UTC, ftoromanoff commented on scripts/createCache.py
> +def Cut_OPI(filename, tile_dir, image_name, origin, tileSize, tile, out_raster_srs):
Fait (j'en ai peut être raté encore quelque une)

2020-11-13 09:48 UTC, ftoromanoff commented on scripts/createCache.py
> +    ecriture = False
Fait

2020-11-13 13:25 UTC, amrosu commented on scripts/createCache.py
> +    ecriture = False
pas complétement, il y a encore des variables en français

2020-11-13 16:06 UTC, amrosu requested changes
J'ai fait des tests sur 4 opi cv2 et les temps ne sont pas vraiment différents entre mono (16m41s) et multi (14m40)
Et pour les tests avec 3 opi vxl (1h17m pour mono) et (55m54s pour multi) - pour le moment, je n'arrive pas à les visualiser dans itowns ces caches vxl (pas de problème avec les caches cv2), je ne sais pas encore trop pourquoi

2020-11-13 16:06 UTC, amrosu commented on scripts/createCache.py
> +def cut_opi_1tile(filename, tile_dir, image_name, origin, tileSize, tile, out_raster_srs, nb_canaux):
variable en français -> à mettre en anglais pour garder la cohérence

2020-11-16 08:18 UTC, ftoromanoff commented on scripts/createCache.py
> +    print(" ", nb_tiles, "tuiles a traitées")
Fait

2020-11-16 08:27 UTC, ftoromanoff commented on scripts/createCache.py
> +        print("  ",advancement,"% terminée")
C'est du au fait que les différents process sont fait en parallèles et ne prennent pas le même temps.
Je demande au programme d'écrire un pourcentage au moment ou il démarre le nième process correspondant a ce pourcentage. (Ex pour 100 OPI, j'écrit 10% quand il commence a traiter la 10eme image etc...)
Pour faire mieux il faudrait lier les process et verrouiller des variable et je pense que ca ferait perdre du temps...)

2020-11-16 08:27 UTC, ftoromanoff commented on scripts/createCache.py
> +def cut_opi_1tile(filename, tile_dir, image_name, origin, tileSize, tile, out_raster_srs, nb_canaux):
Corrigé

2020-11-18 12:53 UTC, amrosu commented on scripts/createCache.py
> +        print("  ",advancement,"% terminée")
J'ai remplacé par une barre d'avancement

2020-11-19 11:02 UTC, amrosu approved these changes

2020-11-19 11:03 UTC, gmaillet approved these changes

2020-11-19 15:33 UTC, closed without merging