Level as param
ign-packo/PackO pull request #74
Opened 2020-11-24 08:40 UTC by ftoromanoff

Création du cache:

- ajout d'un argument pour paramétrer les niveaux de pyramide à calculer (--level)
Ce paramètre peut être un 'int' unique ou deux 'int' définissant le level min et le level max

Suppression du paramètre api devenu obsolète (depuis une version précédente)

2020-11-24 10:52 UTC, gmaillet requested changes
Tu as mis nargs à '+', donc l'utilisateur peut donner un nombre libre de valeur et il pourrait avoir l'idée de spécifier les niveaux un à un  (même si le help parle de "range"):
-l 10 11 12 13 14
Actuellement, le programme ne prend en compte que les deux premières valeurs (donc 10 et 11 sur cet exemple).
Je ne pense qu'il faudrait envoyer une exception si l'utilisateur donne plus de 2 valeurs.

2020-11-24 10:57 UTC, ftoromanoff commented
> Tu as mis nargs à '+', donc l'utilisateur peut donner un nombre libre de valeur et il pourrait avoir l'idée de spécifier les niveaux un à un (même si le help parle de "range"):
> -l 10 11 12 13 14
> Actuellement, le programme ne prend en compte que les deux premières valeurs (donc 10 et 11 sur cet exemple).
> Je ne pense qu'il faudrait envoyer une exception si l'utilisateur donne plus de 2 valeurs.

L'idée est de ne pouvoir entrer que des niveaux consécutifs donc un niveau min et un niveau max (ou un unique niveau ) pour ne pas avoir à tester si toutes les valeurs entrées sont bien consécutives.

2020-11-24 11:04 UTC, gmaillet commented
> > Tu as mis nargs à '+', donc l'utilisateur peut donner un nombre libre de valeur et il pourrait avoir l'idée de spécifier les niveaux un à un (même si le help parle de "range"):
> > -l 10 11 12 13 14
> > Actuellement, le programme ne prend en compte que les deux premières valeurs (donc 10 et 11 sur cet exemple).
> > Je ne pense qu'il faudrait envoyer une exception si l'utilisateur donne plus de 2 valeurs.
> 
> L'idée est de ne pouvoir entrer que des niveaux consécutifs donc un niveau min et un niveau max (ou un unique niveau ) pour ne pas avoir à tester si toutes les valeurs entrées sont bien consécutives.

Je suis d'accord avec toi, l'idée c'est de gérer soit:
- rien (on fait tous les niveaux de la config)
- un niveau unique
- un min/max
Mais du coup, je demande à retourner une exception si l'utilisateur à l'idée étrange de mettre 3 valeurs ou plus (ce qui est techniquement autorisé avec le nargs à '+').

2020-11-24 11:05 UTC, ftoromanoff commented
> > > Tu as mis nargs à '+', donc l'utilisateur peut donner un nombre libre de valeur et il pourrait avoir l'idée de spécifier les niveaux un à un (même si le help parle de "range"):
> > > -l 10 11 12 13 14
> > > Actuellement, le programme ne prend en compte que les deux premières valeurs (donc 10 et 11 sur cet exemple).
> > > Je ne pense qu'il faudrait envoyer une exception si l'utilisateur donne plus de 2 valeurs.
> > 
> > 
> > L'idée est de ne pouvoir entrer que des niveaux consécutifs donc un niveau min et un niveau max (ou un unique niveau ) pour ne pas avoir à tester si toutes les valeurs entrées sont bien consécutives.
> 
> Je suis d'accord avec toi, l'idée c'est de gérer soit:
> 
> * rien (on fait tous les niveaux de la config)
> * un niveau unique
> * un min/max
>   Mais du coup, je demande à retourner une exception si l'utilisateur à l'idée étrange de mettre 3 valeurs ou plus (ce qui est techniquement autorisé avec le nargs à '+').

Tout a fait d'accord, j'était aussi en train de me rendre compte qu'il y avait pas de message d'erreur quand on entre plus que 2 arguments.

Je corrige ca !

2020-11-24 13:34 UTC, gmaillet approved these changes

2020-11-27 14:32 UTC, gmaillet requested changes
- gestion automatique du min/max
- création d'une erreur si les niveaux demandés ne sont pas dans la pyramide utilisée
- erreur si niveau négatif

2020-11-27 16:33 UTC, ftoromanoff commented
> * gestion automatique du min/max
> * création d'une erreur si les niveaux demandés ne sont pas dans la pyramide utilisée
Corrigé

> * erreur si niveau négatif
A mettre dans le fichier update_cache (dans create_cache le fichier overviews est crée à la volé)

2020-11-30 08:58 UTC, merged