Update cache and factoring
ign-packo/PackO pull request #75
Opened 2020-11-25 14:13 UTC by ftoromanoff

Gestion du cache :
- ajout d'un script permettant l'ajout d'image a un cache existant (update_cache.py)
- refactoring des fonctions communes à la création et la mise a jour d'un cache dans un fichier commun (cache_function.py)

2020-11-30 11:11 UTC, ftoromanoff commented
Renommage  : cache_function.py -> cache.py

2020-12-01 08:05 UTC, gmaillet requested changes
Je n'ai pas encore tout vérifié, mais il faut mettre à jour le script .github/workflows/lint-python.yml pour scanner tous les '.py' et plus uniquement le create_cache.py
Sur ma machine pylint m'a signalé quelques problème d'indentation et de la duplication de code entre les fichiers

2020-12-02 09:45 UTC, ftoromanoff commented
Correction du bug quand il n'y a pas de -l spécifié

2020-12-11 09:23 UTC, amrosu approved these changes

2020-12-11 09:23 UTC, gmaillet commented
@ftoromanoff à rebaser avant le merge

2020-12-11 14:41 UTC, gmaillet approved these changes

2020-12-11 14:45 UTC, merged