Fix level for select
ign-packo/PackO pull request #78
Opened 2020-12-01 11:45 UTC by ftoromanoff

Fix de la sélection d'une nouvelle OPI lorsque le niveau max n'a pas été généré

Actuellement, le niveau max est codé en dur dans le code et est égal au niveau max.
Or l'on peut maintenant générer des caches qui ne vont plus calculer la pyramide pour le niveau maximal.

2020-12-02 09:22 UTC, gmaillet requested changes
- Il pourrait être sympa de considérer que lorsqu'il n'y a pas de balise "computed", on dispose implicitement de tous les niveaux.
- Je pense qu'il y a des corrections complémentaires à faire dans les autres routes (patch, wmts) pour gérer que tous les niveaux ne sont peut-être pas dispo dans le cache

2020-12-02 10:46 UTC, ftoromanoff commented
> * Il pourrait être sympa de considérer que lorsqu'il n'y a pas de balise "computed", on dispose implicitement de tous les niveaux.

Potentiellement compliqué d'effacer la balise "computed" lorsque l'on fait un update_cache avec les levels manquants ?
(j'ai d'ailleurs supprimé la balise "computed" pour la remplacer par une balise "level" avec min et max dans "dataSet")

> * Je pense qu'il y a des corrections complémentaires à faire dans les autres routes (patch, wmts) pour gérer que tous les niveaux ne sont peut-être pas dispo dans le cache

J'ai modifié les routes wmts pour ne faire apparaitre que les niveaux réellement disponibles dans le cache, et les routes patchs pour ne renvoyer que les tuiles existantes

2020-12-07 13:18 UTC, gmaillet approved these changes

2020-12-08 14:21 UTC, amrosu requested changes
Il faut corriger bug quand "-l" pas indiqué - faire un cherry-pick du commit correspondant sur la branche  updateCache - je n'ai pas testé la correction, mais elle doit se trouver sur cette branche

2020-12-08 14:26 UTC, ftoromanoff commented
> Il faut corriger bug quand "-l" pas indiqué - faire un cherry-pick du commit correspondant sur la branche updateCache - je n'ai pas testé la correction, mais elle doit se trouver sur cette branche

Cette correction est normalement déja présente sur cette branche mais pas sur autre

2020-12-08 14:45 UTC, ftoromanoff commented
> Il faut corriger bug quand "-l" pas indiqué - faire un cherry-pick du commit correspondant sur la branche updateCache - je n'ai pas testé la correction, mais elle doit se trouver sur cette branche

Corrigé

2020-12-08 19:00 UTC, amrosu approved these changes

2020-12-09 08:56 UTC, merged