Mise en place des chemins "façon ROK4"
ign-packo/PackO pull request #80
Opened 2020-12-07 16:14 UTC by gmaillet

Pour le moment cette PR modifie:
- le code de l'API (les routes wmts, graph, patch)
- les ressources (ajout d'un attribut pathDepth dans le overview)
- le cache_test

Mais il reste encore à modifier les scripts de création et de mise à jour du cache (en attente de #75 et #78)

2021-01-05 16:10 UTC, ftoromanoff requested changes
J'ai créer un nouveau cache a l'aide de create_cache et update_cache. Tout à l'air de fonctionner.
Il faudrait juste vérifier exactement ce qui est entendu par 'pathDepth' dans Rok4.

2021-01-05 16:16 UTC, ftoromanoff commented on routes/graph.js
> +  const url = `${path.join(global.dir_cache, 'graph', rok4.getTileRoot(Tx, Ty, lvlMax, overviews.pathDepth))}.png`;
ne serait il pas plus lisible d'écrire :
const url = path.join(global.dir_cache, 'graph', `${rok4.getTileRoot(Tx, Ty, lvlMax, overviews.pathDepth)}.png`)
?

2021-01-07 12:05 UTC, gmaillet commented on routes/graph.js
> +  const url = `${path.join(global.dir_cache, 'graph', rok4.getTileRoot(Tx, Ty, lvlMax, overviews.pathDepth))}.png`;
pris en compte dans le commit 9957369

2021-01-08 14:05 UTC, gmaillet commented on cache_test/overviews.json
> +	"pathDepth": 3,
Pris en compte dans 334a5c0

2021-01-08 14:16 UTC, gmaillet commented
@ftoromanoff j'ai pris en compte tes deux remarques, peux-tu refaire une review stp

2021-01-11 09:57 UTC, ftoromanoff commented on routes/patch.js
> +  // const pathProcess = require('path');
const rok4 = require('../rok4.js'); manquant ?
J'obtiens une erreur lors de la creation d'un patch :
patch on a reçu une erreur :  ReferenceError: rok4 is not defined
    at Function.createPatch (eval at run (D:\PackO\node_modules\workerpool\src\worker.js:100:11), <anonymous>:57:20)
    at Function.run (D:\PackO\node_modules\workerpool\src\worker.js:101:12)
    at MessagePort.<anonymous> (D:\PackO\node_modules\workerpool\src\worker.js:121:27)
    at MessagePort.[nodejs.internal.kHybridDispatch] (internal/event_target.js:354:41)
    at MessagePort.exports.emitMessage (internal/per_context/messageport.js:18:26)

2021-01-12 08:15 UTC, ftoromanoff approved these changes

2021-01-12 12:49 UTC, merged