Visualisation des saisie et Sauvegarde des saisie
ign-packo/PackO pull request #91
Opened 2021-01-20 15:17 UTC by ftoromanoff

Cette PR ajoute deux fonctionnalités :

- l'ajout d'une couche vectorielle 'retouches' permettant la visualisation de l'ensemble des patchs actifs (à tout instants)
- un bouton 'save' permettant la sauvegarde de tous les patchs actifs

Autre modification
- rok4.js => retour en 2 parties dirPath et fileName (et non plus une unique string)
- patch.js => Corr de bug :
  - clear : suppression des fichiers dans les tuiles touchées par les patchs non actifs

2021-01-29 10:07 UTC, gmaillet commented
Pour le save: conserver l'historique des patchs dans un fichier avec la date et l'heure.

2021-01-29 14:15 UTC, ftoromanoff commented
> Pour le save: conserver un fichier d'historique des patchs à chaque fois que l'on fait un save avec la date et l'heure dans le nom du fichier.

lors du save, il y a copie du fichier activePatchs.json dans un fichier save_yyyymmddhhmm.json.

2021-01-29 14:40 UTC, amrosu commented
Il serait bien d'ajouter les secondes (save_yyyymmddhhmmss.json)  pour éviter les conflits de noms

2021-01-29 14:46 UTC, ftoromanoff commented
> Il serait bien d'ajouter les secondes (save_yyyymmddhhmmss.json) pour éviter les conflits de noms

Ajouté.

2021-01-29 15:42 UTC, amrosu requested changes

2021-01-29 15:42 UTC, amrosu commented on routes/patch.js
> +  const date = new Date(Date.now()).toLocaleString().replace(/ |à|:|\//g, '').substr(0, 14);
"toLocaleString" n'est pas une bonne idée pour le nom du fichier. 
Si la locale n'est pas en français ça ne va pas marcher. La locale peut aussi changer entre l'OS de la machine et celle d'un docker par exemple. Par exemple, j'obtiens : 
> console.log(new Date(Date.now()).toLocaleString().replace(/ |à|:|\//g, '').substr(0, 14));
1292021,32101P

Et même en français, on a ça : 
> console.log(new Date(Date.now()).toLocaleString().replace(/ |à|:|\//g, '').substr(0, 14));
29012021162537

Le format est donc ddmmyyy... et pas celui que tu disais (yyyymmdd...), et donc le tri alphabétique des fichiers ne représentera pas la temporalité.

La bonne pratique est de simplement utiliser "toISOString" qui est fait exprès pour ça. Quelle que soit la locale, j'obtiens :
> console.log(new Date(Date.now()).toISOString().replace(/ |:|\//g, '_'));
2021-01-29T15_35_57.263Z 

(Note : je pense qu'il est important de garder le Z final qui indique le fuseau horaire)

2021-01-29 15:48 UTC, ftoromanoff commented on routes/patch.js
> +  const date = new Date(Date.now()).toLocaleString().replace(/ |à|:|\//g, '').substr(0, 14);
j'avais commencé par utiliser toISOString, mais c'est l'heure UTC et j'ai donc essayé autre chose pour récupérer l'heure 'locale'.
Du coup tu recommandes de garder l'heure UTC ?

2021-01-29 16:10 UTC, amrosu commented on routes/patch.js
> +  const date = new Date(Date.now()).toLocaleString().replace(/ |à|:|\//g, '').substr(0, 14);
Oui, en gardant le Z.

2021-01-29 16:16 UTC, ftoromanoff commented on routes/patch.js
> +  const date = new Date(Date.now()).toLocaleString().replace(/ |à|:|\//g, '').substr(0, 14);
Le nom du fichier est maintenant save_yyyymmddhhmmssZ.json. (En heure UTC)

2021-02-01 12:42 UTC, gmaillet commented
Je n'ai pas fait une analyse complète, mais je constate une perte de précision en Y entre les polygones saisies et ceux qui s'affichent (le fameux million du L93). Je ne sais pas à quel niveau ça se produit.

2021-02-02 17:17 UTC, amrosu requested changes
Il semble y avoir un bug sur les saisies. Si j'en fais sur un cache avec niveaux par défaut (lmin=10, lmax=21), je retrouve bien les polygones dans les json du cache (save inclus), mais elles n'ont pas d'effet sur le mosaïquage

2021-02-02 17:59 UTC, amrosu commented
Et j'ai l'impression que le temps de recharge après la fermeture d'un polygone et de sauvegarde des polygones est assez long, même sur un jeu de données très petit

2021-02-02 19:37 UTC, amrosu commented
> Il semble y avoir un bug sur les saisies. Si j'en fais sur un cache avec niveaux par défaut (lmin=10, lmax=21), je retrouve bien les polygones dans les json du cache (save inclus), mais elles n'ont pas d'effet sur le mosaïquage

Il semblerait que ça soit lié à l'utilisation des workers à l'étape "process patch" : dès que le polygone est un peu grand et qu'il décide d'utiliser les workers, ça ne marche plus, la saisie n'a plus d'effet

2021-02-03 09:57 UTC, ftoromanoff commented on itowns/index.js
> +        opacity: 0.5,
Fait, mais je demande confirmation avec Gerald pour un petit bug possible

2021-02-03 09:57 UTC, ftoromanoff commented on itowns/Saisie.js
> +    let redrawRetouches = false;
Bonne idée, j'avais un peu sécher sur le nom^^
Modifié

2021-06-08 09:56 UTC, closed without merging