[itowns/index] Saisie de coord et centrage
ign-packo/PackO pull request #92
Opened 2021-01-22 10:10 UTC by ftoromanoff

Nouvelle fonctionnalité 
- centrage de la carte sur des coordonnées renseignées à la main

2021-02-01 12:37 UTC, gmaillet approved these changes

2021-02-01 16:25 UTC, amrosu requested changes

2021-02-01 16:25 UTC, amrosu commented on itowns/index.js
> +        saisie.message = 'Coordonnees non valides';
Si on a saisi une fois des coordonnées erronées (ex: mauvais format), j'ai l'impression que, si par la suite on saisit des coordonnées valides, il se positionne bien, mais il garde néanmoins ce message ("Coordonnées non valides") qui est désormais plus vrai. Ce message est enlevé uniquement par remplacement : si on clique ailleurs dans le menu, le message qui accompagne cette action le remplacera

2021-02-02 16:29 UTC, ftoromanoff commented on itowns/index.js
> +        saisie.message = 'Coordonnees non valides';
J'ai modifié la façon dont les modifications de la fenêtre 'coord' sont prises en compte pour pouvoir mettre à jour le message en temps réel.

2021-02-03 12:54 UTC, amrosu commented
La vérification du format des coordonnées saisies est faite en utilisant une expression régulière qui définit ce qui est accepté en tant que float

2021-02-03 12:58 UTC, amrosu approved these changes

2021-02-04 11:09 UTC, merged